//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2/9/2023 12:16:29 PM
namespace SAPB1
{
    /// <summary>
    /// There are no comments for AddressExtension in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("AddressExtension")]
    public partial class AddressExtension : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property ShipToStreet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ShipToStreet")]
        public virtual string ShipToStreet
        {
            get
            {
                return this._ShipToStreet;
            }
            set
            {
                this.OnShipToStreetChanging(value);
                this._ShipToStreet = value;
                this.OnShipToStreetChanged();
                this.OnPropertyChanged("ShipToStreet");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ShipToStreet;
        partial void OnShipToStreetChanging(string value);
        partial void OnShipToStreetChanged();
        /// <summary>
        /// There are no comments for Property ShipToStreetNo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ShipToStreetNo")]
        public virtual string ShipToStreetNo
        {
            get
            {
                return this._ShipToStreetNo;
            }
            set
            {
                this.OnShipToStreetNoChanging(value);
                this._ShipToStreetNo = value;
                this.OnShipToStreetNoChanged();
                this.OnPropertyChanged("ShipToStreetNo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ShipToStreetNo;
        partial void OnShipToStreetNoChanging(string value);
        partial void OnShipToStreetNoChanged();
        /// <summary>
        /// There are no comments for Property ShipToBlock in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ShipToBlock")]
        public virtual string ShipToBlock
        {
            get
            {
                return this._ShipToBlock;
            }
            set
            {
                this.OnShipToBlockChanging(value);
                this._ShipToBlock = value;
                this.OnShipToBlockChanged();
                this.OnPropertyChanged("ShipToBlock");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ShipToBlock;
        partial void OnShipToBlockChanging(string value);
        partial void OnShipToBlockChanged();
        /// <summary>
        /// There are no comments for Property ShipToBuilding in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ShipToBuilding")]
        public virtual string ShipToBuilding
        {
            get
            {
                return this._ShipToBuilding;
            }
            set
            {
                this.OnShipToBuildingChanging(value);
                this._ShipToBuilding = value;
                this.OnShipToBuildingChanged();
                this.OnPropertyChanged("ShipToBuilding");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ShipToBuilding;
        partial void OnShipToBuildingChanging(string value);
        partial void OnShipToBuildingChanged();
        /// <summary>
        /// There are no comments for Property ShipToCity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ShipToCity")]
        public virtual string ShipToCity
        {
            get
            {
                return this._ShipToCity;
            }
            set
            {
                this.OnShipToCityChanging(value);
                this._ShipToCity = value;
                this.OnShipToCityChanged();
                this.OnPropertyChanged("ShipToCity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ShipToCity;
        partial void OnShipToCityChanging(string value);
        partial void OnShipToCityChanged();
        /// <summary>
        /// There are no comments for Property ShipToZipCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ShipToZipCode")]
        public virtual string ShipToZipCode
        {
            get
            {
                return this._ShipToZipCode;
            }
            set
            {
                this.OnShipToZipCodeChanging(value);
                this._ShipToZipCode = value;
                this.OnShipToZipCodeChanged();
                this.OnPropertyChanged("ShipToZipCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ShipToZipCode;
        partial void OnShipToZipCodeChanging(string value);
        partial void OnShipToZipCodeChanged();
        /// <summary>
        /// There are no comments for Property ShipToCounty in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ShipToCounty")]
        public virtual string ShipToCounty
        {
            get
            {
                return this._ShipToCounty;
            }
            set
            {
                this.OnShipToCountyChanging(value);
                this._ShipToCounty = value;
                this.OnShipToCountyChanged();
                this.OnPropertyChanged("ShipToCounty");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ShipToCounty;
        partial void OnShipToCountyChanging(string value);
        partial void OnShipToCountyChanged();
        /// <summary>
        /// There are no comments for Property ShipToState in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ShipToState")]
        public virtual string ShipToState
        {
            get
            {
                return this._ShipToState;
            }
            set
            {
                this.OnShipToStateChanging(value);
                this._ShipToState = value;
                this.OnShipToStateChanged();
                this.OnPropertyChanged("ShipToState");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ShipToState;
        partial void OnShipToStateChanging(string value);
        partial void OnShipToStateChanged();
        /// <summary>
        /// There are no comments for Property ShipToCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ShipToCountry")]
        public virtual string ShipToCountry
        {
            get
            {
                return this._ShipToCountry;
            }
            set
            {
                this.OnShipToCountryChanging(value);
                this._ShipToCountry = value;
                this.OnShipToCountryChanged();
                this.OnPropertyChanged("ShipToCountry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ShipToCountry;
        partial void OnShipToCountryChanging(string value);
        partial void OnShipToCountryChanged();
        /// <summary>
        /// There are no comments for Property ShipToAddressType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ShipToAddressType")]
        public virtual string ShipToAddressType
        {
            get
            {
                return this._ShipToAddressType;
            }
            set
            {
                this.OnShipToAddressTypeChanging(value);
                this._ShipToAddressType = value;
                this.OnShipToAddressTypeChanged();
                this.OnPropertyChanged("ShipToAddressType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ShipToAddressType;
        partial void OnShipToAddressTypeChanging(string value);
        partial void OnShipToAddressTypeChanged();
        /// <summary>
        /// There are no comments for Property BillToStreet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BillToStreet")]
        public virtual string BillToStreet
        {
            get
            {
                return this._BillToStreet;
            }
            set
            {
                this.OnBillToStreetChanging(value);
                this._BillToStreet = value;
                this.OnBillToStreetChanged();
                this.OnPropertyChanged("BillToStreet");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _BillToStreet;
        partial void OnBillToStreetChanging(string value);
        partial void OnBillToStreetChanged();
        /// <summary>
        /// There are no comments for Property BillToStreetNo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BillToStreetNo")]
        public virtual string BillToStreetNo
        {
            get
            {
                return this._BillToStreetNo;
            }
            set
            {
                this.OnBillToStreetNoChanging(value);
                this._BillToStreetNo = value;
                this.OnBillToStreetNoChanged();
                this.OnPropertyChanged("BillToStreetNo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _BillToStreetNo;
        partial void OnBillToStreetNoChanging(string value);
        partial void OnBillToStreetNoChanged();
        /// <summary>
        /// There are no comments for Property BillToBlock in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BillToBlock")]
        public virtual string BillToBlock
        {
            get
            {
                return this._BillToBlock;
            }
            set
            {
                this.OnBillToBlockChanging(value);
                this._BillToBlock = value;
                this.OnBillToBlockChanged();
                this.OnPropertyChanged("BillToBlock");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _BillToBlock;
        partial void OnBillToBlockChanging(string value);
        partial void OnBillToBlockChanged();
        /// <summary>
        /// There are no comments for Property BillToBuilding in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BillToBuilding")]
        public virtual string BillToBuilding
        {
            get
            {
                return this._BillToBuilding;
            }
            set
            {
                this.OnBillToBuildingChanging(value);
                this._BillToBuilding = value;
                this.OnBillToBuildingChanged();
                this.OnPropertyChanged("BillToBuilding");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _BillToBuilding;
        partial void OnBillToBuildingChanging(string value);
        partial void OnBillToBuildingChanged();
        /// <summary>
        /// There are no comments for Property BillToCity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BillToCity")]
        public virtual string BillToCity
        {
            get
            {
                return this._BillToCity;
            }
            set
            {
                this.OnBillToCityChanging(value);
                this._BillToCity = value;
                this.OnBillToCityChanged();
                this.OnPropertyChanged("BillToCity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _BillToCity;
        partial void OnBillToCityChanging(string value);
        partial void OnBillToCityChanged();
        /// <summary>
        /// There are no comments for Property BillToZipCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BillToZipCode")]
        public virtual string BillToZipCode
        {
            get
            {
                return this._BillToZipCode;
            }
            set
            {
                this.OnBillToZipCodeChanging(value);
                this._BillToZipCode = value;
                this.OnBillToZipCodeChanged();
                this.OnPropertyChanged("BillToZipCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _BillToZipCode;
        partial void OnBillToZipCodeChanging(string value);
        partial void OnBillToZipCodeChanged();
        /// <summary>
        /// There are no comments for Property BillToCounty in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BillToCounty")]
        public virtual string BillToCounty
        {
            get
            {
                return this._BillToCounty;
            }
            set
            {
                this.OnBillToCountyChanging(value);
                this._BillToCounty = value;
                this.OnBillToCountyChanged();
                this.OnPropertyChanged("BillToCounty");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _BillToCounty;
        partial void OnBillToCountyChanging(string value);
        partial void OnBillToCountyChanged();
        /// <summary>
        /// There are no comments for Property BillToState in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BillToState")]
        public virtual string BillToState
        {
            get
            {
                return this._BillToState;
            }
            set
            {
                this.OnBillToStateChanging(value);
                this._BillToState = value;
                this.OnBillToStateChanged();
                this.OnPropertyChanged("BillToState");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _BillToState;
        partial void OnBillToStateChanging(string value);
        partial void OnBillToStateChanged();
        /// <summary>
        /// There are no comments for Property BillToCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BillToCountry")]
        public virtual string BillToCountry
        {
            get
            {
                return this._BillToCountry;
            }
            set
            {
                this.OnBillToCountryChanging(value);
                this._BillToCountry = value;
                this.OnBillToCountryChanged();
                this.OnPropertyChanged("BillToCountry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _BillToCountry;
        partial void OnBillToCountryChanging(string value);
        partial void OnBillToCountryChanged();
        /// <summary>
        /// There are no comments for Property BillToAddressType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BillToAddressType")]
        public virtual string BillToAddressType
        {
            get
            {
                return this._BillToAddressType;
            }
            set
            {
                this.OnBillToAddressTypeChanging(value);
                this._BillToAddressType = value;
                this.OnBillToAddressTypeChanged();
                this.OnPropertyChanged("BillToAddressType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _BillToAddressType;
        partial void OnBillToAddressTypeChanging(string value);
        partial void OnBillToAddressTypeChanged();
        /// <summary>
        /// There are no comments for Property ShipToGlobalLocationNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ShipToGlobalLocationNumber")]
        public virtual string ShipToGlobalLocationNumber
        {
            get
            {
                return this._ShipToGlobalLocationNumber;
            }
            set
            {
                this.OnShipToGlobalLocationNumberChanging(value);
                this._ShipToGlobalLocationNumber = value;
                this.OnShipToGlobalLocationNumberChanged();
                this.OnPropertyChanged("ShipToGlobalLocationNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ShipToGlobalLocationNumber;
        partial void OnShipToGlobalLocationNumberChanging(string value);
        partial void OnShipToGlobalLocationNumberChanged();
        /// <summary>
        /// There are no comments for Property BillToGlobalLocationNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BillToGlobalLocationNumber")]
        public virtual string BillToGlobalLocationNumber
        {
            get
            {
                return this._BillToGlobalLocationNumber;
            }
            set
            {
                this.OnBillToGlobalLocationNumberChanging(value);
                this._BillToGlobalLocationNumber = value;
                this.OnBillToGlobalLocationNumberChanged();
                this.OnPropertyChanged("BillToGlobalLocationNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _BillToGlobalLocationNumber;
        partial void OnBillToGlobalLocationNumberChanging(string value);
        partial void OnBillToGlobalLocationNumberChanged();
        /// <summary>
        /// There are no comments for Property ShipToAddress2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ShipToAddress2")]
        public virtual string ShipToAddress2
        {
            get
            {
                return this._ShipToAddress2;
            }
            set
            {
                this.OnShipToAddress2Changing(value);
                this._ShipToAddress2 = value;
                this.OnShipToAddress2Changed();
                this.OnPropertyChanged("ShipToAddress2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ShipToAddress2;
        partial void OnShipToAddress2Changing(string value);
        partial void OnShipToAddress2Changed();
        /// <summary>
        /// There are no comments for Property ShipToAddress3 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ShipToAddress3")]
        public virtual string ShipToAddress3
        {
            get
            {
                return this._ShipToAddress3;
            }
            set
            {
                this.OnShipToAddress3Changing(value);
                this._ShipToAddress3 = value;
                this.OnShipToAddress3Changed();
                this.OnPropertyChanged("ShipToAddress3");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ShipToAddress3;
        partial void OnShipToAddress3Changing(string value);
        partial void OnShipToAddress3Changed();
        /// <summary>
        /// There are no comments for Property BillToAddress2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BillToAddress2")]
        public virtual string BillToAddress2
        {
            get
            {
                return this._BillToAddress2;
            }
            set
            {
                this.OnBillToAddress2Changing(value);
                this._BillToAddress2 = value;
                this.OnBillToAddress2Changed();
                this.OnPropertyChanged("BillToAddress2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _BillToAddress2;
        partial void OnBillToAddress2Changing(string value);
        partial void OnBillToAddress2Changed();
        /// <summary>
        /// There are no comments for Property BillToAddress3 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BillToAddress3")]
        public virtual string BillToAddress3
        {
            get
            {
                return this._BillToAddress3;
            }
            set
            {
                this.OnBillToAddress3Changing(value);
                this._BillToAddress3 = value;
                this.OnBillToAddress3Changed();
                this.OnPropertyChanged("BillToAddress3");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _BillToAddress3;
        partial void OnBillToAddress3Changing(string value);
        partial void OnBillToAddress3Changed();
        /// <summary>
        /// There are no comments for Property PlaceOfSupply in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PlaceOfSupply")]
        public virtual string PlaceOfSupply
        {
            get
            {
                return this._PlaceOfSupply;
            }
            set
            {
                this.OnPlaceOfSupplyChanging(value);
                this._PlaceOfSupply = value;
                this.OnPlaceOfSupplyChanged();
                this.OnPropertyChanged("PlaceOfSupply");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _PlaceOfSupply;
        partial void OnPlaceOfSupplyChanging(string value);
        partial void OnPlaceOfSupplyChanged();
        /// <summary>
        /// There are no comments for Property PurchasePlaceOfSupply in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PurchasePlaceOfSupply")]
        public virtual string PurchasePlaceOfSupply
        {
            get
            {
                return this._PurchasePlaceOfSupply;
            }
            set
            {
                this.OnPurchasePlaceOfSupplyChanging(value);
                this._PurchasePlaceOfSupply = value;
                this.OnPurchasePlaceOfSupplyChanged();
                this.OnPropertyChanged("PurchasePlaceOfSupply");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _PurchasePlaceOfSupply;
        partial void OnPurchasePlaceOfSupplyChanging(string value);
        partial void OnPurchasePlaceOfSupplyChanged();
        /// <summary>
        /// There are no comments for Property DocEntry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DocEntry")]
        public virtual global::System.Nullable<int> DocEntry
        {
            get
            {
                return this._DocEntry;
            }
            set
            {
                this.OnDocEntryChanging(value);
                this._DocEntry = value;
                this.OnDocEntryChanged();
                this.OnPropertyChanged("DocEntry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _DocEntry;
        partial void OnDocEntryChanging(global::System.Nullable<int> value);
        partial void OnDocEntryChanged();
        /// <summary>
        /// There are no comments for Property GoodsIssuePlaceBP in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("GoodsIssuePlaceBP")]
        public virtual string GoodsIssuePlaceBP
        {
            get
            {
                return this._GoodsIssuePlaceBP;
            }
            set
            {
                this.OnGoodsIssuePlaceBPChanging(value);
                this._GoodsIssuePlaceBP = value;
                this.OnGoodsIssuePlaceBPChanged();
                this.OnPropertyChanged("GoodsIssuePlaceBP");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _GoodsIssuePlaceBP;
        partial void OnGoodsIssuePlaceBPChanging(string value);
        partial void OnGoodsIssuePlaceBPChanged();
        /// <summary>
        /// There are no comments for Property GoodsIssuePlaceCNPJ in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("GoodsIssuePlaceCNPJ")]
        public virtual string GoodsIssuePlaceCNPJ
        {
            get
            {
                return this._GoodsIssuePlaceCNPJ;
            }
            set
            {
                this.OnGoodsIssuePlaceCNPJChanging(value);
                this._GoodsIssuePlaceCNPJ = value;
                this.OnGoodsIssuePlaceCNPJChanged();
                this.OnPropertyChanged("GoodsIssuePlaceCNPJ");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _GoodsIssuePlaceCNPJ;
        partial void OnGoodsIssuePlaceCNPJChanging(string value);
        partial void OnGoodsIssuePlaceCNPJChanged();
        /// <summary>
        /// There are no comments for Property GoodsIssuePlaceCPF in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("GoodsIssuePlaceCPF")]
        public virtual string GoodsIssuePlaceCPF
        {
            get
            {
                return this._GoodsIssuePlaceCPF;
            }
            set
            {
                this.OnGoodsIssuePlaceCPFChanging(value);
                this._GoodsIssuePlaceCPF = value;
                this.OnGoodsIssuePlaceCPFChanged();
                this.OnPropertyChanged("GoodsIssuePlaceCPF");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _GoodsIssuePlaceCPF;
        partial void OnGoodsIssuePlaceCPFChanging(string value);
        partial void OnGoodsIssuePlaceCPFChanged();
        /// <summary>
        /// There are no comments for Property GoodsIssuePlaceStreet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("GoodsIssuePlaceStreet")]
        public virtual string GoodsIssuePlaceStreet
        {
            get
            {
                return this._GoodsIssuePlaceStreet;
            }
            set
            {
                this.OnGoodsIssuePlaceStreetChanging(value);
                this._GoodsIssuePlaceStreet = value;
                this.OnGoodsIssuePlaceStreetChanged();
                this.OnPropertyChanged("GoodsIssuePlaceStreet");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _GoodsIssuePlaceStreet;
        partial void OnGoodsIssuePlaceStreetChanging(string value);
        partial void OnGoodsIssuePlaceStreetChanged();
        /// <summary>
        /// There are no comments for Property GoodsIssuePlaceStreetNo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("GoodsIssuePlaceStreetNo")]
        public virtual string GoodsIssuePlaceStreetNo
        {
            get
            {
                return this._GoodsIssuePlaceStreetNo;
            }
            set
            {
                this.OnGoodsIssuePlaceStreetNoChanging(value);
                this._GoodsIssuePlaceStreetNo = value;
                this.OnGoodsIssuePlaceStreetNoChanged();
                this.OnPropertyChanged("GoodsIssuePlaceStreetNo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _GoodsIssuePlaceStreetNo;
        partial void OnGoodsIssuePlaceStreetNoChanging(string value);
        partial void OnGoodsIssuePlaceStreetNoChanged();
        /// <summary>
        /// There are no comments for Property GoodsIssuePlaceBuilding in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("GoodsIssuePlaceBuilding")]
        public virtual string GoodsIssuePlaceBuilding
        {
            get
            {
                return this._GoodsIssuePlaceBuilding;
            }
            set
            {
                this.OnGoodsIssuePlaceBuildingChanging(value);
                this._GoodsIssuePlaceBuilding = value;
                this.OnGoodsIssuePlaceBuildingChanged();
                this.OnPropertyChanged("GoodsIssuePlaceBuilding");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _GoodsIssuePlaceBuilding;
        partial void OnGoodsIssuePlaceBuildingChanging(string value);
        partial void OnGoodsIssuePlaceBuildingChanged();
        /// <summary>
        /// There are no comments for Property GoodsIssuePlaceZip in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("GoodsIssuePlaceZip")]
        public virtual string GoodsIssuePlaceZip
        {
            get
            {
                return this._GoodsIssuePlaceZip;
            }
            set
            {
                this.OnGoodsIssuePlaceZipChanging(value);
                this._GoodsIssuePlaceZip = value;
                this.OnGoodsIssuePlaceZipChanged();
                this.OnPropertyChanged("GoodsIssuePlaceZip");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _GoodsIssuePlaceZip;
        partial void OnGoodsIssuePlaceZipChanging(string value);
        partial void OnGoodsIssuePlaceZipChanged();
        /// <summary>
        /// There are no comments for Property GoodsIssuePlaceBlock in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("GoodsIssuePlaceBlock")]
        public virtual string GoodsIssuePlaceBlock
        {
            get
            {
                return this._GoodsIssuePlaceBlock;
            }
            set
            {
                this.OnGoodsIssuePlaceBlockChanging(value);
                this._GoodsIssuePlaceBlock = value;
                this.OnGoodsIssuePlaceBlockChanged();
                this.OnPropertyChanged("GoodsIssuePlaceBlock");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _GoodsIssuePlaceBlock;
        partial void OnGoodsIssuePlaceBlockChanging(string value);
        partial void OnGoodsIssuePlaceBlockChanged();
        /// <summary>
        /// There are no comments for Property GoodsIssuePlaceCity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("GoodsIssuePlaceCity")]
        public virtual string GoodsIssuePlaceCity
        {
            get
            {
                return this._GoodsIssuePlaceCity;
            }
            set
            {
                this.OnGoodsIssuePlaceCityChanging(value);
                this._GoodsIssuePlaceCity = value;
                this.OnGoodsIssuePlaceCityChanged();
                this.OnPropertyChanged("GoodsIssuePlaceCity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _GoodsIssuePlaceCity;
        partial void OnGoodsIssuePlaceCityChanging(string value);
        partial void OnGoodsIssuePlaceCityChanged();
        /// <summary>
        /// There are no comments for Property GoodsIssuePlaceCounty in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("GoodsIssuePlaceCounty")]
        public virtual string GoodsIssuePlaceCounty
        {
            get
            {
                return this._GoodsIssuePlaceCounty;
            }
            set
            {
                this.OnGoodsIssuePlaceCountyChanging(value);
                this._GoodsIssuePlaceCounty = value;
                this.OnGoodsIssuePlaceCountyChanged();
                this.OnPropertyChanged("GoodsIssuePlaceCounty");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _GoodsIssuePlaceCounty;
        partial void OnGoodsIssuePlaceCountyChanging(string value);
        partial void OnGoodsIssuePlaceCountyChanged();
        /// <summary>
        /// There are no comments for Property GoodsIssuePlaceState in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("GoodsIssuePlaceState")]
        public virtual string GoodsIssuePlaceState
        {
            get
            {
                return this._GoodsIssuePlaceState;
            }
            set
            {
                this.OnGoodsIssuePlaceStateChanging(value);
                this._GoodsIssuePlaceState = value;
                this.OnGoodsIssuePlaceStateChanged();
                this.OnPropertyChanged("GoodsIssuePlaceState");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _GoodsIssuePlaceState;
        partial void OnGoodsIssuePlaceStateChanging(string value);
        partial void OnGoodsIssuePlaceStateChanged();
        /// <summary>
        /// There are no comments for Property GoodsIssuePlaceCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("GoodsIssuePlaceCountry")]
        public virtual string GoodsIssuePlaceCountry
        {
            get
            {
                return this._GoodsIssuePlaceCountry;
            }
            set
            {
                this.OnGoodsIssuePlaceCountryChanging(value);
                this._GoodsIssuePlaceCountry = value;
                this.OnGoodsIssuePlaceCountryChanged();
                this.OnPropertyChanged("GoodsIssuePlaceCountry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _GoodsIssuePlaceCountry;
        partial void OnGoodsIssuePlaceCountryChanging(string value);
        partial void OnGoodsIssuePlaceCountryChanged();
        /// <summary>
        /// There are no comments for Property GoodsIssuePlacePhone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("GoodsIssuePlacePhone")]
        public virtual string GoodsIssuePlacePhone
        {
            get
            {
                return this._GoodsIssuePlacePhone;
            }
            set
            {
                this.OnGoodsIssuePlacePhoneChanging(value);
                this._GoodsIssuePlacePhone = value;
                this.OnGoodsIssuePlacePhoneChanged();
                this.OnPropertyChanged("GoodsIssuePlacePhone");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _GoodsIssuePlacePhone;
        partial void OnGoodsIssuePlacePhoneChanging(string value);
        partial void OnGoodsIssuePlacePhoneChanged();
        /// <summary>
        /// There are no comments for Property GoodsIssuePlaceEMail in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("GoodsIssuePlaceEMail")]
        public virtual string GoodsIssuePlaceEMail
        {
            get
            {
                return this._GoodsIssuePlaceEMail;
            }
            set
            {
                this.OnGoodsIssuePlaceEMailChanging(value);
                this._GoodsIssuePlaceEMail = value;
                this.OnGoodsIssuePlaceEMailChanged();
                this.OnPropertyChanged("GoodsIssuePlaceEMail");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _GoodsIssuePlaceEMail;
        partial void OnGoodsIssuePlaceEMailChanging(string value);
        partial void OnGoodsIssuePlaceEMailChanged();
        /// <summary>
        /// There are no comments for Property GoodsIssuePlaceDepartureDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("GoodsIssuePlaceDepartureDate")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> GoodsIssuePlaceDepartureDate
        {
            get
            {
                return this._GoodsIssuePlaceDepartureDate;
            }
            set
            {
                this.OnGoodsIssuePlaceDepartureDateChanging(value);
                this._GoodsIssuePlaceDepartureDate = value;
                this.OnGoodsIssuePlaceDepartureDateChanged();
                this.OnPropertyChanged("GoodsIssuePlaceDepartureDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _GoodsIssuePlaceDepartureDate;
        partial void OnGoodsIssuePlaceDepartureDateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnGoodsIssuePlaceDepartureDateChanged();
        /// <summary>
        /// There are no comments for Property DeliveryPlaceBP in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DeliveryPlaceBP")]
        public virtual string DeliveryPlaceBP
        {
            get
            {
                return this._DeliveryPlaceBP;
            }
            set
            {
                this.OnDeliveryPlaceBPChanging(value);
                this._DeliveryPlaceBP = value;
                this.OnDeliveryPlaceBPChanged();
                this.OnPropertyChanged("DeliveryPlaceBP");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DeliveryPlaceBP;
        partial void OnDeliveryPlaceBPChanging(string value);
        partial void OnDeliveryPlaceBPChanged();
        /// <summary>
        /// There are no comments for Property DeliveryPlaceCNPJ in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DeliveryPlaceCNPJ")]
        public virtual string DeliveryPlaceCNPJ
        {
            get
            {
                return this._DeliveryPlaceCNPJ;
            }
            set
            {
                this.OnDeliveryPlaceCNPJChanging(value);
                this._DeliveryPlaceCNPJ = value;
                this.OnDeliveryPlaceCNPJChanged();
                this.OnPropertyChanged("DeliveryPlaceCNPJ");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DeliveryPlaceCNPJ;
        partial void OnDeliveryPlaceCNPJChanging(string value);
        partial void OnDeliveryPlaceCNPJChanged();
        /// <summary>
        /// There are no comments for Property DeliveryPlaceCPF in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DeliveryPlaceCPF")]
        public virtual string DeliveryPlaceCPF
        {
            get
            {
                return this._DeliveryPlaceCPF;
            }
            set
            {
                this.OnDeliveryPlaceCPFChanging(value);
                this._DeliveryPlaceCPF = value;
                this.OnDeliveryPlaceCPFChanged();
                this.OnPropertyChanged("DeliveryPlaceCPF");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DeliveryPlaceCPF;
        partial void OnDeliveryPlaceCPFChanging(string value);
        partial void OnDeliveryPlaceCPFChanged();
        /// <summary>
        /// There are no comments for Property DeliveryPlaceStreet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DeliveryPlaceStreet")]
        public virtual string DeliveryPlaceStreet
        {
            get
            {
                return this._DeliveryPlaceStreet;
            }
            set
            {
                this.OnDeliveryPlaceStreetChanging(value);
                this._DeliveryPlaceStreet = value;
                this.OnDeliveryPlaceStreetChanged();
                this.OnPropertyChanged("DeliveryPlaceStreet");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DeliveryPlaceStreet;
        partial void OnDeliveryPlaceStreetChanging(string value);
        partial void OnDeliveryPlaceStreetChanged();
        /// <summary>
        /// There are no comments for Property DeliveryPlaceStreetNo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DeliveryPlaceStreetNo")]
        public virtual string DeliveryPlaceStreetNo
        {
            get
            {
                return this._DeliveryPlaceStreetNo;
            }
            set
            {
                this.OnDeliveryPlaceStreetNoChanging(value);
                this._DeliveryPlaceStreetNo = value;
                this.OnDeliveryPlaceStreetNoChanged();
                this.OnPropertyChanged("DeliveryPlaceStreetNo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DeliveryPlaceStreetNo;
        partial void OnDeliveryPlaceStreetNoChanging(string value);
        partial void OnDeliveryPlaceStreetNoChanged();
        /// <summary>
        /// There are no comments for Property DeliveryPlaceBuilding in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DeliveryPlaceBuilding")]
        public virtual string DeliveryPlaceBuilding
        {
            get
            {
                return this._DeliveryPlaceBuilding;
            }
            set
            {
                this.OnDeliveryPlaceBuildingChanging(value);
                this._DeliveryPlaceBuilding = value;
                this.OnDeliveryPlaceBuildingChanged();
                this.OnPropertyChanged("DeliveryPlaceBuilding");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DeliveryPlaceBuilding;
        partial void OnDeliveryPlaceBuildingChanging(string value);
        partial void OnDeliveryPlaceBuildingChanged();
        /// <summary>
        /// There are no comments for Property DeliveryPlaceZip in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DeliveryPlaceZip")]
        public virtual string DeliveryPlaceZip
        {
            get
            {
                return this._DeliveryPlaceZip;
            }
            set
            {
                this.OnDeliveryPlaceZipChanging(value);
                this._DeliveryPlaceZip = value;
                this.OnDeliveryPlaceZipChanged();
                this.OnPropertyChanged("DeliveryPlaceZip");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DeliveryPlaceZip;
        partial void OnDeliveryPlaceZipChanging(string value);
        partial void OnDeliveryPlaceZipChanged();
        /// <summary>
        /// There are no comments for Property DeliveryPlaceBlock in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DeliveryPlaceBlock")]
        public virtual string DeliveryPlaceBlock
        {
            get
            {
                return this._DeliveryPlaceBlock;
            }
            set
            {
                this.OnDeliveryPlaceBlockChanging(value);
                this._DeliveryPlaceBlock = value;
                this.OnDeliveryPlaceBlockChanged();
                this.OnPropertyChanged("DeliveryPlaceBlock");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DeliveryPlaceBlock;
        partial void OnDeliveryPlaceBlockChanging(string value);
        partial void OnDeliveryPlaceBlockChanged();
        /// <summary>
        /// There are no comments for Property DeliveryPlaceCity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DeliveryPlaceCity")]
        public virtual string DeliveryPlaceCity
        {
            get
            {
                return this._DeliveryPlaceCity;
            }
            set
            {
                this.OnDeliveryPlaceCityChanging(value);
                this._DeliveryPlaceCity = value;
                this.OnDeliveryPlaceCityChanged();
                this.OnPropertyChanged("DeliveryPlaceCity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DeliveryPlaceCity;
        partial void OnDeliveryPlaceCityChanging(string value);
        partial void OnDeliveryPlaceCityChanged();
        /// <summary>
        /// There are no comments for Property DeliveryPlaceCounty in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DeliveryPlaceCounty")]
        public virtual string DeliveryPlaceCounty
        {
            get
            {
                return this._DeliveryPlaceCounty;
            }
            set
            {
                this.OnDeliveryPlaceCountyChanging(value);
                this._DeliveryPlaceCounty = value;
                this.OnDeliveryPlaceCountyChanged();
                this.OnPropertyChanged("DeliveryPlaceCounty");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DeliveryPlaceCounty;
        partial void OnDeliveryPlaceCountyChanging(string value);
        partial void OnDeliveryPlaceCountyChanged();
        /// <summary>
        /// There are no comments for Property DeliveryPlaceState in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DeliveryPlaceState")]
        public virtual string DeliveryPlaceState
        {
            get
            {
                return this._DeliveryPlaceState;
            }
            set
            {
                this.OnDeliveryPlaceStateChanging(value);
                this._DeliveryPlaceState = value;
                this.OnDeliveryPlaceStateChanged();
                this.OnPropertyChanged("DeliveryPlaceState");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DeliveryPlaceState;
        partial void OnDeliveryPlaceStateChanging(string value);
        partial void OnDeliveryPlaceStateChanged();
        /// <summary>
        /// There are no comments for Property DeliveryPlaceCountry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DeliveryPlaceCountry")]
        public virtual string DeliveryPlaceCountry
        {
            get
            {
                return this._DeliveryPlaceCountry;
            }
            set
            {
                this.OnDeliveryPlaceCountryChanging(value);
                this._DeliveryPlaceCountry = value;
                this.OnDeliveryPlaceCountryChanged();
                this.OnPropertyChanged("DeliveryPlaceCountry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DeliveryPlaceCountry;
        partial void OnDeliveryPlaceCountryChanging(string value);
        partial void OnDeliveryPlaceCountryChanged();
        /// <summary>
        /// There are no comments for Property DeliveryPlacePhone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DeliveryPlacePhone")]
        public virtual string DeliveryPlacePhone
        {
            get
            {
                return this._DeliveryPlacePhone;
            }
            set
            {
                this.OnDeliveryPlacePhoneChanging(value);
                this._DeliveryPlacePhone = value;
                this.OnDeliveryPlacePhoneChanged();
                this.OnPropertyChanged("DeliveryPlacePhone");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DeliveryPlacePhone;
        partial void OnDeliveryPlacePhoneChanging(string value);
        partial void OnDeliveryPlacePhoneChanged();
        /// <summary>
        /// There are no comments for Property DeliveryPlaceEMail in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DeliveryPlaceEMail")]
        public virtual string DeliveryPlaceEMail
        {
            get
            {
                return this._DeliveryPlaceEMail;
            }
            set
            {
                this.OnDeliveryPlaceEMailChanging(value);
                this._DeliveryPlaceEMail = value;
                this.OnDeliveryPlaceEMailChanged();
                this.OnPropertyChanged("DeliveryPlaceEMail");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DeliveryPlaceEMail;
        partial void OnDeliveryPlaceEMailChanging(string value);
        partial void OnDeliveryPlaceEMailChanged();
        /// <summary>
        /// There are no comments for Property DeliveryPlaceDepartureDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DeliveryPlaceDepartureDate")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> DeliveryPlaceDepartureDate
        {
            get
            {
                return this._DeliveryPlaceDepartureDate;
            }
            set
            {
                this.OnDeliveryPlaceDepartureDateChanging(value);
                this._DeliveryPlaceDepartureDate = value;
                this.OnDeliveryPlaceDepartureDateChanged();
                this.OnPropertyChanged("DeliveryPlaceDepartureDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _DeliveryPlaceDepartureDate;
        partial void OnDeliveryPlaceDepartureDateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDeliveryPlaceDepartureDateChanged();
        /// <summary>
        /// There are no comments for Property U_B1SYS_DIR3_01 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("U_B1SYS_DIR3_01")]
        public virtual string U_B1SYS_DIR3_01
        {
            get
            {
                return this._U_B1SYS_DIR3_01;
            }
            set
            {
                this.OnU_B1SYS_DIR3_01Changing(value);
                this._U_B1SYS_DIR3_01 = value;
                this.OnU_B1SYS_DIR3_01Changed();
                this.OnPropertyChanged("U_B1SYS_DIR3_01");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _U_B1SYS_DIR3_01;
        partial void OnU_B1SYS_DIR3_01Changing(string value);
        partial void OnU_B1SYS_DIR3_01Changed();
        /// <summary>
        /// There are no comments for Property U_B1SYS_DIR3_02 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("U_B1SYS_DIR3_02")]
        public virtual string U_B1SYS_DIR3_02
        {
            get
            {
                return this._U_B1SYS_DIR3_02;
            }
            set
            {
                this.OnU_B1SYS_DIR3_02Changing(value);
                this._U_B1SYS_DIR3_02 = value;
                this.OnU_B1SYS_DIR3_02Changed();
                this.OnPropertyChanged("U_B1SYS_DIR3_02");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _U_B1SYS_DIR3_02;
        partial void OnU_B1SYS_DIR3_02Changing(string value);
        partial void OnU_B1SYS_DIR3_02Changed();
        /// <summary>
        /// There are no comments for Property U_B1SYS_DIR3_03 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("U_B1SYS_DIR3_03")]
        public virtual string U_B1SYS_DIR3_03
        {
            get
            {
                return this._U_B1SYS_DIR3_03;
            }
            set
            {
                this.OnU_B1SYS_DIR3_03Changing(value);
                this._U_B1SYS_DIR3_03 = value;
                this.OnU_B1SYS_DIR3_03Changed();
                this.OnPropertyChanged("U_B1SYS_DIR3_03");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _U_B1SYS_DIR3_03;
        partial void OnU_B1SYS_DIR3_03Changing(string value);
        partial void OnU_B1SYS_DIR3_03Changed();
        /// <summary>
        /// There are no comments for Property DynamicProperties in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DynamicProperties")]
        public virtual global::System.Collections.Generic.IDictionary<string, object> DynamicProperties
        {
            get
            {
                return this._DynamicProperties;
            }
            set
            {
                this.OnDynamicPropertiesChanging(value);
                this._DynamicProperties = value;
                this.OnDynamicPropertiesChanged();
                this.OnPropertyChanged("DynamicProperties");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.Generic.IDictionary<string, object> _DynamicProperties = new global::System.Collections.Generic.Dictionary<string, object>();
        partial void OnDynamicPropertiesChanging(global::System.Collections.Generic.IDictionary<string, object> value);
        partial void OnDynamicPropertiesChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
