//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2/9/2023 12:16:29 PM
namespace SAPB1
{
    /// <summary>
    /// There are no comments for ApprovalTemplateDocument in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ApprovalTemplateDocument")]
    public partial class ApprovalTemplateDocument : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property DocumentType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DocumentType")]
        public virtual global::System.Nullable<global::SAPB1.ApprovalTemplatesDocumentTypeEnum> DocumentType
        {
            get
            {
                return this._DocumentType;
            }
            set
            {
                this.OnDocumentTypeChanging(value);
                this._DocumentType = value;
                this.OnDocumentTypeChanged();
                this.OnPropertyChanged("DocumentType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::SAPB1.ApprovalTemplatesDocumentTypeEnum> _DocumentType;
        partial void OnDocumentTypeChanging(global::System.Nullable<global::SAPB1.ApprovalTemplatesDocumentTypeEnum> value);
        partial void OnDocumentTypeChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
