//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2/9/2023 12:16:29 PM
namespace SAPB1
{
    /// <summary>
    /// There are no comments for AutomaticPostingEnum in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("AutomaticPostingEnum")]
    public enum AutomaticPostingEnum
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("apNo")]
        ApNo = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("apInterestAndFee")]
        ApInterestAndFee = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("apInterestOnly")]
        ApInterestOnly = 2,
        [global::Microsoft.OData.Client.OriginalNameAttribute("apFeeOnly")]
        ApFeeOnly = 3
    }
}
