//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2/9/2023 12:16:29 PM
namespace SAPB1
{
    /// <summary>
    /// There are no comments for BoBarCodeStandardEnum in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("BoBarCodeStandardEnum")]
    public enum BoBarCodeStandardEnum
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("rlbsan13")]
        Rlbsan13 = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("rlbsCode39")]
        RlbsCode39 = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("rlbsCode128")]
        RlbsCode128 = 2
    }
}
