//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2/9/2023 12:16:29 PM
namespace SAPB1
{
    /// <summary>
    /// There are no comments for BoCardTypes in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("BoCardTypes")]
    public enum BoCardTypes
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("cCustomer")]
        CCustomer = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("cSupplier")]
        CSupplier = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("cLid")]
        CLid = 2
    }
}
