//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2/9/2023 12:16:29 PM
namespace SAPB1
{
    /// <summary>
    /// There are no comments for BoDocumentLinePickStatus in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("BoDocumentLinePickStatus")]
    public enum BoDocumentLinePickStatus
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("dlps_Picked")]
        Dlps_Picked = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("dlps_NotPicked")]
        Dlps_NotPicked = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("dlps_ReleasedForPicking")]
        Dlps_ReleasedForPicking = 2,
        [global::Microsoft.OData.Client.OriginalNameAttribute("dlps_PartiallyPicked")]
        Dlps_PartiallyPicked = 3
    }
}
