//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2/9/2023 12:16:29 PM
namespace SAPB1
{
    /// <summary>
    /// There are no comments for BoMsgRcpTypes in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("BoMsgRcpTypes")]
    public enum BoMsgRcpTypes
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("rt_RandomUser")]
        Rt_RandomUser = -1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("rt_ContactPerson")]
        Rt_ContactPerson = 11,
        [global::Microsoft.OData.Client.OriginalNameAttribute("rt_InternalUser")]
        Rt_InternalUser = 12
    }
}
