//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2/9/2023 12:16:29 PM
namespace SAPB1
{
    /// <summary>
    /// There are no comments for BoPictureSizeEnum in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("BoPictureSizeEnum")]
    public enum BoPictureSizeEnum
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("rlpsOriginalSize")]
        RlpsOriginalSize = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("rlpsFitFieldSizeNonProportionally")]
        RlpsFitFieldSizeNonProportionally = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("rlpsFitFieldSizeProportionally")]
        RlpsFitFieldSizeProportionally = 2,
        [global::Microsoft.OData.Client.OriginalNameAttribute("rlpsFitFieldHeight")]
        RlpsFitFieldHeight = 3,
        [global::Microsoft.OData.Client.OriginalNameAttribute("rlpsFitFieldWidth")]
        RlpsFitFieldWidth = 4
    }
}
