//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2/9/2023 12:16:29 PM
namespace SAPB1
{
    /// <summary>
    /// There are no comments for BoRoundingMethod in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("BoRoundingMethod")]
    public enum BoRoundingMethod
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("borm_FixedEnding")]
        Borm_FixedEnding = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("borm_FixedInterval")]
        Borm_FixedInterval = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("borm_NoRounding")]
        Borm_NoRounding = 2,
        [global::Microsoft.OData.Client.OriginalNameAttribute("borm_RoundToFullAmount")]
        Borm_RoundToFullAmount = 3,
        [global::Microsoft.OData.Client.OriginalNameAttribute("borm_RoundToFullDecAmount")]
        Borm_RoundToFullDecAmount = 4,
        [global::Microsoft.OData.Client.OriginalNameAttribute("borm_RoundToFullTensAmount")]
        Borm_RoundToFullTensAmount = 5
    }
}
