//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2/9/2023 12:16:29 PM
namespace SAPB1
{
    /// <summary>
    /// There are no comments for BPPrioritySingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("BPPrioritySingle")]
    public partial class BPPrioritySingle : global::Microsoft.OData.Client.DataServiceQuerySingle<BPPriority>
    {
        /// <summary>
        /// Initialize a new BPPrioritySingle object.
        /// </summary>
        public BPPrioritySingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new BPPrioritySingle object.
        /// </summary>
        public BPPrioritySingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new BPPrioritySingle object.
        /// </summary>
        public BPPrioritySingle(global::Microsoft.OData.Client.DataServiceQuerySingle<BPPriority> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for BusinessPartners in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BusinessPartners")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::SAPB1.BusinessPartner> BusinessPartners
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._BusinessPartners == null))
                {
                    this._BusinessPartners = Context.CreateQuery<global::SAPB1.BusinessPartner>(GetPath("BusinessPartners"));
                }
                return this._BusinessPartners;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::SAPB1.BusinessPartner> _BusinessPartners;
    }
    /// <summary>
    /// There are no comments for BPPriority in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Priority
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Priority")]
    [global::Microsoft.OData.Client.EntitySet("BPPriorities")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("BPPriority")]
    public partial class BPPriority : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new BPPriority object.
        /// </summary>
        /// <param name="priority">Initial value of Priority.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static BPPriority CreateBPPriority(int priority)
        {
            BPPriority bPPriority = new BPPriority();
            bPPriority.Priority = priority;
            return bPPriority;
        }
        /// <summary>
        /// There are no comments for Property Priority in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Priority")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Priority is required.")]
        public virtual int Priority
        {
            get
            {
                return this._Priority;
            }
            set
            {
                this.OnPriorityChanging(value);
                this._Priority = value;
                this.OnPriorityChanged();
                this.OnPropertyChanged("Priority");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Priority;
        partial void OnPriorityChanging(int value);
        partial void OnPriorityChanged();
        /// <summary>
        /// There are no comments for Property PriorityDescription in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PriorityDescription")]
        public virtual string PriorityDescription
        {
            get
            {
                return this._PriorityDescription;
            }
            set
            {
                this.OnPriorityDescriptionChanging(value);
                this._PriorityDescription = value;
                this.OnPriorityDescriptionChanged();
                this.OnPropertyChanged("PriorityDescription");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _PriorityDescription;
        partial void OnPriorityDescriptionChanging(string value);
        partial void OnPriorityDescriptionChanged();
        /// <summary>
        /// There are no comments for Property BusinessPartners in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BusinessPartners")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::SAPB1.BusinessPartner> BusinessPartners
        {
            get
            {
                return this._BusinessPartners;
            }
            set
            {
                this.OnBusinessPartnersChanging(value);
                this._BusinessPartners = value;
                this.OnBusinessPartnersChanged();
                this.OnPropertyChanged("BusinessPartners");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::SAPB1.BusinessPartner> _BusinessPartners = new global::Microsoft.OData.Client.DataServiceCollection<global::SAPB1.BusinessPartner>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnBusinessPartnersChanging(global::Microsoft.OData.Client.DataServiceCollection<global::SAPB1.BusinessPartner> value);
        partial void OnBusinessPartnersChanged();
        /// <summary>
        /// There are no comments for Property DynamicProperties in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DynamicProperties")]
        public virtual global::System.Collections.Generic.IDictionary<string, object> DynamicProperties
        {
            get
            {
                return this._DynamicProperties;
            }
            set
            {
                this.OnDynamicPropertiesChanging(value);
                this._DynamicProperties = value;
                this.OnDynamicPropertiesChanged();
                this.OnPropertyChanged("DynamicProperties");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.Generic.IDictionary<string, object> _DynamicProperties = new global::System.Collections.Generic.Dictionary<string, object>();
        partial void OnDynamicPropertiesChanging(global::System.Collections.Generic.IDictionary<string, object> value);
        partial void OnDynamicPropertiesChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
