//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2/9/2023 12:16:29 PM
namespace SAPB1
{
    /// <summary>
    /// There are no comments for BudgetLine in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("BudgetLine")]
    public partial class BudgetLine : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property PrecentOfAnnualBudgetAmount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PrecentOfAnnualBudgetAmount")]
        public virtual global::System.Nullable<double> PrecentOfAnnualBudgetAmount
        {
            get
            {
                return this._PrecentOfAnnualBudgetAmount;
            }
            set
            {
                this.OnPrecentOfAnnualBudgetAmountChanging(value);
                this._PrecentOfAnnualBudgetAmount = value;
                this.OnPrecentOfAnnualBudgetAmountChanged();
                this.OnPropertyChanged("PrecentOfAnnualBudgetAmount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _PrecentOfAnnualBudgetAmount;
        partial void OnPrecentOfAnnualBudgetAmountChanging(global::System.Nullable<double> value);
        partial void OnPrecentOfAnnualBudgetAmountChanged();
        /// <summary>
        /// There are no comments for Property RowDetails in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("RowDetails")]
        public virtual string RowDetails
        {
            get
            {
                return this._RowDetails;
            }
            set
            {
                this.OnRowDetailsChanging(value);
                this._RowDetails = value;
                this.OnRowDetailsChanged();
                this.OnPropertyChanged("RowDetails");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _RowDetails;
        partial void OnRowDetailsChanging(string value);
        partial void OnRowDetailsChanged();
        /// <summary>
        /// There are no comments for Property RowNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("RowNumber")]
        public virtual global::System.Nullable<int> RowNumber
        {
            get
            {
                return this._RowNumber;
            }
            set
            {
                this.OnRowNumberChanging(value);
                this._RowNumber = value;
                this.OnRowNumberChanged();
                this.OnPropertyChanged("RowNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _RowNumber;
        partial void OnRowNumberChanging(global::System.Nullable<int> value);
        partial void OnRowNumberChanged();
        /// <summary>
        /// There are no comments for Property FutExpenSysDebit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("FutExpenSysDebit")]
        public virtual global::System.Nullable<double> FutExpenSysDebit
        {
            get
            {
                return this._FutExpenSysDebit;
            }
            set
            {
                this.OnFutExpenSysDebitChanging(value);
                this._FutExpenSysDebit = value;
                this.OnFutExpenSysDebitChanged();
                this.OnPropertyChanged("FutExpenSysDebit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _FutExpenSysDebit;
        partial void OnFutExpenSysDebitChanging(global::System.Nullable<double> value);
        partial void OnFutExpenSysDebitChanged();
        /// <summary>
        /// There are no comments for Property FutExpenDebit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("FutExpenDebit")]
        public virtual global::System.Nullable<double> FutExpenDebit
        {
            get
            {
                return this._FutExpenDebit;
            }
            set
            {
                this.OnFutExpenDebitChanging(value);
                this._FutExpenDebit = value;
                this.OnFutExpenDebitChanged();
                this.OnPropertyChanged("FutExpenDebit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _FutExpenDebit;
        partial void OnFutExpenDebitChanging(global::System.Nullable<double> value);
        partial void OnFutExpenDebitChanged();
        /// <summary>
        /// There are no comments for Property FutExpenSysCredit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("FutExpenSysCredit")]
        public virtual global::System.Nullable<double> FutExpenSysCredit
        {
            get
            {
                return this._FutExpenSysCredit;
            }
            set
            {
                this.OnFutExpenSysCreditChanging(value);
                this._FutExpenSysCredit = value;
                this.OnFutExpenSysCreditChanged();
                this.OnPropertyChanged("FutExpenSysCredit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _FutExpenSysCredit;
        partial void OnFutExpenSysCreditChanging(global::System.Nullable<double> value);
        partial void OnFutExpenSysCreditChanged();
        /// <summary>
        /// There are no comments for Property FutExpenCredit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("FutExpenCredit")]
        public virtual global::System.Nullable<double> FutExpenCredit
        {
            get
            {
                return this._FutExpenCredit;
            }
            set
            {
                this.OnFutExpenCreditChanging(value);
                this._FutExpenCredit = value;
                this.OnFutExpenCreditChanged();
                this.OnPropertyChanged("FutExpenCredit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _FutExpenCredit;
        partial void OnFutExpenCreditChanging(global::System.Nullable<double> value);
        partial void OnFutExpenCreditChanged();
        /// <summary>
        /// There are no comments for Property FutIncomesSysCredit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("FutIncomesSysCredit")]
        public virtual global::System.Nullable<double> FutIncomesSysCredit
        {
            get
            {
                return this._FutIncomesSysCredit;
            }
            set
            {
                this.OnFutIncomesSysCreditChanging(value);
                this._FutIncomesSysCredit = value;
                this.OnFutIncomesSysCreditChanged();
                this.OnPropertyChanged("FutIncomesSysCredit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _FutIncomesSysCredit;
        partial void OnFutIncomesSysCreditChanging(global::System.Nullable<double> value);
        partial void OnFutIncomesSysCreditChanged();
        /// <summary>
        /// There are no comments for Property FutIncomesSysDebit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("FutIncomesSysDebit")]
        public virtual global::System.Nullable<double> FutIncomesSysDebit
        {
            get
            {
                return this._FutIncomesSysDebit;
            }
            set
            {
                this.OnFutIncomesSysDebitChanging(value);
                this._FutIncomesSysDebit = value;
                this.OnFutIncomesSysDebitChanged();
                this.OnPropertyChanged("FutIncomesSysDebit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _FutIncomesSysDebit;
        partial void OnFutIncomesSysDebitChanging(global::System.Nullable<double> value);
        partial void OnFutIncomesSysDebitChanged();
        /// <summary>
        /// There are no comments for Property FutIncomesCredit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("FutIncomesCredit")]
        public virtual global::System.Nullable<double> FutIncomesCredit
        {
            get
            {
                return this._FutIncomesCredit;
            }
            set
            {
                this.OnFutIncomesCreditChanging(value);
                this._FutIncomesCredit = value;
                this.OnFutIncomesCreditChanged();
                this.OnPropertyChanged("FutIncomesCredit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _FutIncomesCredit;
        partial void OnFutIncomesCreditChanging(global::System.Nullable<double> value);
        partial void OnFutIncomesCreditChanged();
        /// <summary>
        /// There are no comments for Property BudgetSysTotDebit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BudgetSysTotDebit")]
        public virtual global::System.Nullable<double> BudgetSysTotDebit
        {
            get
            {
                return this._BudgetSysTotDebit;
            }
            set
            {
                this.OnBudgetSysTotDebitChanging(value);
                this._BudgetSysTotDebit = value;
                this.OnBudgetSysTotDebitChanged();
                this.OnPropertyChanged("BudgetSysTotDebit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _BudgetSysTotDebit;
        partial void OnBudgetSysTotDebitChanging(global::System.Nullable<double> value);
        partial void OnBudgetSysTotDebitChanged();
        /// <summary>
        /// There are no comments for Property BalSysTotDebit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BalSysTotDebit")]
        public virtual global::System.Nullable<double> BalSysTotDebit
        {
            get
            {
                return this._BalSysTotDebit;
            }
            set
            {
                this.OnBalSysTotDebitChanging(value);
                this._BalSysTotDebit = value;
                this.OnBalSysTotDebitChanged();
                this.OnPropertyChanged("BalSysTotDebit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _BalSysTotDebit;
        partial void OnBalSysTotDebitChanging(global::System.Nullable<double> value);
        partial void OnBalSysTotDebitChanged();
        /// <summary>
        /// There are no comments for Property BalTotDebit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BalTotDebit")]
        public virtual global::System.Nullable<double> BalTotDebit
        {
            get
            {
                return this._BalTotDebit;
            }
            set
            {
                this.OnBalTotDebitChanging(value);
                this._BalTotDebit = value;
                this.OnBalTotDebitChanged();
                this.OnPropertyChanged("BalTotDebit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _BalTotDebit;
        partial void OnBalTotDebitChanging(global::System.Nullable<double> value);
        partial void OnBalTotDebitChanged();
        /// <summary>
        /// There are no comments for Property BudgetTotCredit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BudgetTotCredit")]
        public virtual global::System.Nullable<double> BudgetTotCredit
        {
            get
            {
                return this._BudgetTotCredit;
            }
            set
            {
                this.OnBudgetTotCreditChanging(value);
                this._BudgetTotCredit = value;
                this.OnBudgetTotCreditChanged();
                this.OnPropertyChanged("BudgetTotCredit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _BudgetTotCredit;
        partial void OnBudgetTotCreditChanging(global::System.Nullable<double> value);
        partial void OnBudgetTotCreditChanged();
        /// <summary>
        /// There are no comments for Property BudgetSysTotCredit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BudgetSysTotCredit")]
        public virtual global::System.Nullable<double> BudgetSysTotCredit
        {
            get
            {
                return this._BudgetSysTotCredit;
            }
            set
            {
                this.OnBudgetSysTotCreditChanging(value);
                this._BudgetSysTotCredit = value;
                this.OnBudgetSysTotCreditChanged();
                this.OnPropertyChanged("BudgetSysTotCredit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _BudgetSysTotCredit;
        partial void OnBudgetSysTotCreditChanging(global::System.Nullable<double> value);
        partial void OnBudgetSysTotCreditChanged();
        /// <summary>
        /// There are no comments for Property BudgetTotDebit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BudgetTotDebit")]
        public virtual global::System.Nullable<double> BudgetTotDebit
        {
            get
            {
                return this._BudgetTotDebit;
            }
            set
            {
                this.OnBudgetTotDebitChanging(value);
                this._BudgetTotDebit = value;
                this.OnBudgetTotDebitChanged();
                this.OnPropertyChanged("BudgetTotDebit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _BudgetTotDebit;
        partial void OnBudgetTotDebitChanging(global::System.Nullable<double> value);
        partial void OnBudgetTotDebitChanged();
        /// <summary>
        /// There are no comments for Property BalSysTotCredit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BalSysTotCredit")]
        public virtual global::System.Nullable<double> BalSysTotCredit
        {
            get
            {
                return this._BalSysTotCredit;
            }
            set
            {
                this.OnBalSysTotCreditChanging(value);
                this._BalSysTotCredit = value;
                this.OnBalSysTotCreditChanged();
                this.OnPropertyChanged("BalSysTotCredit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _BalSysTotCredit;
        partial void OnBalSysTotCreditChanging(global::System.Nullable<double> value);
        partial void OnBalSysTotCreditChanged();
        /// <summary>
        /// There are no comments for Property BalTotCredit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BalTotCredit")]
        public virtual global::System.Nullable<double> BalTotCredit
        {
            get
            {
                return this._BalTotCredit;
            }
            set
            {
                this.OnBalTotCreditChanging(value);
                this._BalTotCredit = value;
                this.OnBalTotCreditChanged();
                this.OnPropertyChanged("BalTotCredit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _BalTotCredit;
        partial void OnBalTotCreditChanging(global::System.Nullable<double> value);
        partial void OnBalTotCreditChanged();
        /// <summary>
        /// There are no comments for Property BudgetKey in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BudgetKey")]
        public virtual global::System.Nullable<int> BudgetKey
        {
            get
            {
                return this._BudgetKey;
            }
            set
            {
                this.OnBudgetKeyChanging(value);
                this._BudgetKey = value;
                this.OnBudgetKeyChanged();
                this.OnPropertyChanged("BudgetKey");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _BudgetKey;
        partial void OnBudgetKeyChanging(global::System.Nullable<int> value);
        partial void OnBudgetKeyChanged();
        /// <summary>
        /// There are no comments for Property AccountCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AccountCode")]
        public virtual string AccountCode
        {
            get
            {
                return this._AccountCode;
            }
            set
            {
                this.OnAccountCodeChanging(value);
                this._AccountCode = value;
                this.OnAccountCodeChanged();
                this.OnPropertyChanged("AccountCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _AccountCode;
        partial void OnAccountCodeChanging(string value);
        partial void OnAccountCodeChanged();
        /// <summary>
        /// There are no comments for Property FutureIncomeDeb in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("FutureIncomeDeb")]
        public virtual global::System.Nullable<double> FutureIncomeDeb
        {
            get
            {
                return this._FutureIncomeDeb;
            }
            set
            {
                this.OnFutureIncomeDebChanging(value);
                this._FutureIncomeDeb = value;
                this.OnFutureIncomeDebChanged();
                this.OnPropertyChanged("FutureIncomeDeb");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _FutureIncomeDeb;
        partial void OnFutureIncomeDebChanging(global::System.Nullable<double> value);
        partial void OnFutureIncomeDebChanged();
        /// <summary>
        /// There are no comments for Property DynamicProperties in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DynamicProperties")]
        public virtual global::System.Collections.Generic.IDictionary<string, object> DynamicProperties
        {
            get
            {
                return this._DynamicProperties;
            }
            set
            {
                this.OnDynamicPropertiesChanging(value);
                this._DynamicProperties = value;
                this.OnDynamicPropertiesChanged();
                this.OnPropertyChanged("DynamicProperties");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.Generic.IDictionary<string, object> _DynamicProperties = new global::System.Collections.Generic.Dictionary<string, object>();
        partial void OnDynamicPropertiesChanging(global::System.Collections.Generic.IDictionary<string, object> value);
        partial void OnDynamicPropertiesChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
