//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2/9/2023 12:16:29 PM
namespace SAPB1
{
    /// <summary>
    /// There are no comments for ElectronicDocumentEntryLogTypeEnum in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ElectronicDocumentEntryLogTypeEnum")]
    public enum ElectronicDocumentEntryLogTypeEnum
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("edeltNone")]
        EdeltNone = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edeltSend")]
        EdeltSend = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edeltReceive")]
        EdeltReceive = 2,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edeltImport")]
        EdeltImport = 3,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edeltNote")]
        EdeltNote = 4,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edeltWarning")]
        EdeltWarning = 5,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edeltError")]
        EdeltError = 6,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edeltWSData")]
        EdeltWSData = 7
    }
}
