//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2/9/2023 12:16:29 PM
namespace SAPB1
{
    /// <summary>
    /// There are no comments for ElectronicDocumentEntryStatusEnum in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ElectronicDocumentEntryStatusEnum")]
    public enum ElectronicDocumentEntryStatusEnum
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("edesNone")]
        EdesNone = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edesNew")]
        EdesNew = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edesReadyToProcess")]
        EdesReadyToProcess = 2,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edesPending")]
        EdesPending = 3,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edesError")]
        EdesError = 4,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edesOK")]
        EdesOK = 5,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edesSent")]
        EdesSent = 6,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edesDocError")]
        EdesDocError = 7,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edesTempError")]
        EdesTempError = 8,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edesWarning")]
        EdesWarning = 9,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edesWaiting")]
        EdesWaiting = 10,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edesAuthorized")]
        EdesAuthorized = 11,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edesInProcess")]
        EdesInProcess = 12,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edesRejected")]
        EdesRejected = 13,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edesDenied")]
        EdesDenied = 14,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edesCanceled")]
        EdesCanceled = 15,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edesAborted")]
        EdesAborted = 16,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edesUnused")]
        EdesUnused = 17,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edesQueued")]
        EdesQueued = 18,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edesImported")]
        EdesImported = 19,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edesApproved")]
        EdesApproved = 20,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edesApproving")]
        EdesApproving = 21,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edesRejecting")]
        EdesRejecting = 22,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edesGenerated")]
        EdesGenerated = 23,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edesDetermined")]
        EdesDetermined = 24,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edesImporting")]
        EdesImporting = 25
    }
}
