//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2/9/2023 12:16:29 PM
namespace SAPB1
{
    /// <summary>
    /// There are no comments for ElectronicDocProtocolCodeStrEnum in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ElectronicDocProtocolCodeStrEnum")]
    public enum ElectronicDocProtocolCodeStrEnum
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("edpcs_Invalid")]
        Edpcs_Invalid = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edpcs_GEN")]
        Edpcs_GEN = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edpcs_EET")]
        Edpcs_EET = 2,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edpcs_CFDI")]
        Edpcs_CFDI = 3,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edpcs_FPA")]
        Edpcs_FPA = 4,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edpcs_MTD")]
        Edpcs_MTD = 5,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edpcs_EWB")]
        Edpcs_EWB = 6,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edpcs_PEPPOL")]
        Edpcs_PEPPOL = 7,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edpcs_HOI")]
        Edpcs_HOI = 8,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edpcs_MYF")]
        Edpcs_MYF = 9,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edpcs_EIS")]
        Edpcs_EIS = 10,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edpcs_IIS")]
        Edpcs_IIS = 11,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edpcs_IIS_Annual")]
        Edpcs_IIS_Annual = 12,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edpcs_DIGIPOORT")]
        Edpcs_DIGIPOORT = 13,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edpcs_EBooks")]
        Edpcs_EBooks = 14,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edpcs_DOX")]
        Edpcs_DOX = 15,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edpcs_RTIE")]
        Edpcs_RTIE = 16,
        [global::Microsoft.OData.Client.OriginalNameAttribute("edpcs_EBilling")]
        Edpcs_EBilling = 17
    }
}
