//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2/9/2023 12:16:29 PM
namespace SAPB1
{
    /// <summary>
    /// There are no comments for IntrastatConfigurationTriangDealEnum in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("IntrastatConfigurationTriangDealEnum")]
    public enum IntrastatConfigurationTriangDealEnum
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("enNone")]
        EnNone = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("enType11")]
        EnType11 = 11,
        [global::Microsoft.OData.Client.OriginalNameAttribute("enType21")]
        EnType21 = 21,
        [global::Microsoft.OData.Client.OriginalNameAttribute("enType31")]
        EnType31 = 31
    }
}
