//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2/9/2023 12:16:29 PM
namespace SAPB1
{
    /// <summary>
    /// There are no comments for JournalEntryDocumentTypeSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("JournalEntryDocumentTypeSingle")]
    public partial class JournalEntryDocumentTypeSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<JournalEntryDocumentType>
    {
        /// <summary>
        /// Initialize a new JournalEntryDocumentTypeSingle object.
        /// </summary>
        public JournalEntryDocumentTypeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new JournalEntryDocumentTypeSingle object.
        /// </summary>
        public JournalEntryDocumentTypeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new JournalEntryDocumentTypeSingle object.
        /// </summary>
        public JournalEntryDocumentTypeSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<JournalEntryDocumentType> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for JournalEntries in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("JournalEntries")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::SAPB1.JournalEntry> JournalEntries
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._JournalEntries == null))
                {
                    this._JournalEntries = Context.CreateQuery<global::SAPB1.JournalEntry>(GetPath("JournalEntries"));
                }
                return this._JournalEntries;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::SAPB1.JournalEntry> _JournalEntries;
    }
    /// <summary>
    /// There are no comments for JournalEntryDocumentType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// JournalEntryType
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("JournalEntryType")]
    [global::Microsoft.OData.Client.EntitySet("JournalEntryDocumentTypes")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("JournalEntryDocumentType")]
    public partial class JournalEntryDocumentType : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new JournalEntryDocumentType object.
        /// </summary>
        /// <param name="journalEntryType">Initial value of JournalEntryType.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static JournalEntryDocumentType CreateJournalEntryDocumentType(string journalEntryType)
        {
            JournalEntryDocumentType journalEntryDocumentType = new JournalEntryDocumentType();
            journalEntryDocumentType.JournalEntryType = journalEntryType;
            return journalEntryDocumentType;
        }
        /// <summary>
        /// There are no comments for Property JournalEntryType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("JournalEntryType")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "JournalEntryType is required.")]
        public virtual string JournalEntryType
        {
            get
            {
                return this._JournalEntryType;
            }
            set
            {
                this.OnJournalEntryTypeChanging(value);
                this._JournalEntryType = value;
                this.OnJournalEntryTypeChanged();
                this.OnPropertyChanged("JournalEntryType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _JournalEntryType;
        partial void OnJournalEntryTypeChanging(string value);
        partial void OnJournalEntryTypeChanged();
        /// <summary>
        /// There are no comments for Property DocTypeDescription in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DocTypeDescription")]
        public virtual string DocTypeDescription
        {
            get
            {
                return this._DocTypeDescription;
            }
            set
            {
                this.OnDocTypeDescriptionChanging(value);
                this._DocTypeDescription = value;
                this.OnDocTypeDescriptionChanged();
                this.OnPropertyChanged("DocTypeDescription");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DocTypeDescription;
        partial void OnDocTypeDescriptionChanging(string value);
        partial void OnDocTypeDescriptionChanged();
        /// <summary>
        /// There are no comments for Property ShortName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ShortName")]
        public virtual string ShortName
        {
            get
            {
                return this._ShortName;
            }
            set
            {
                this.OnShortNameChanging(value);
                this._ShortName = value;
                this.OnShortNameChanged();
                this.OnPropertyChanged("ShortName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ShortName;
        partial void OnShortNameChanging(string value);
        partial void OnShortNameChanged();
        /// <summary>
        /// There are no comments for Property JournalEntries in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("JournalEntries")]
        public virtual global::Microsoft.OData.Client.DataServiceCollection<global::SAPB1.JournalEntry> JournalEntries
        {
            get
            {
                return this._JournalEntries;
            }
            set
            {
                this.OnJournalEntriesChanging(value);
                this._JournalEntries = value;
                this.OnJournalEntriesChanged();
                this.OnPropertyChanged("JournalEntries");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::SAPB1.JournalEntry> _JournalEntries = new global::Microsoft.OData.Client.DataServiceCollection<global::SAPB1.JournalEntry>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnJournalEntriesChanging(global::Microsoft.OData.Client.DataServiceCollection<global::SAPB1.JournalEntry> value);
        partial void OnJournalEntriesChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
