//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2/9/2023 12:16:29 PM
namespace SAPB1
{
    /// <summary>
    /// There are no comments for PackagesTypeSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("PackagesTypeSingle")]
    public partial class PackagesTypeSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<PackagesType>
    {
        /// <summary>
        /// Initialize a new PackagesTypeSingle object.
        /// </summary>
        public PackagesTypeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new PackagesTypeSingle object.
        /// </summary>
        public PackagesTypeSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new PackagesTypeSingle object.
        /// </summary>
        public PackagesTypeSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<PackagesType> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for PackagesType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Code
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Code")]
    [global::Microsoft.OData.Client.EntitySet("PackagesTypes")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("PackagesType")]
    public partial class PackagesType : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new PackagesType object.
        /// </summary>
        /// <param name="code">Initial value of Code.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static PackagesType CreatePackagesType(int code)
        {
            PackagesType packagesType = new PackagesType();
            packagesType.Code = code;
            return packagesType;
        }
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Type")]
        public virtual string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this._Type = value;
                this.OnTypeChanged();
                this.OnPropertyChanged("Type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Type;
        partial void OnTypeChanging(string value);
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Property Code in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Code")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Code is required.")]
        public virtual int Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                this.OnCodeChanging(value);
                this._Code = value;
                this.OnCodeChanged();
                this.OnPropertyChanged("Code");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Code;
        partial void OnCodeChanging(int value);
        partial void OnCodeChanged();
        /// <summary>
        /// There are no comments for Property Length1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Length1")]
        public virtual global::System.Nullable<double> Length1
        {
            get
            {
                return this._Length1;
            }
            set
            {
                this.OnLength1Changing(value);
                this._Length1 = value;
                this.OnLength1Changed();
                this.OnPropertyChanged("Length1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _Length1;
        partial void OnLength1Changing(global::System.Nullable<double> value);
        partial void OnLength1Changed();
        /// <summary>
        /// There are no comments for Property Length1Unit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Length1Unit")]
        public virtual global::System.Nullable<int> Length1Unit
        {
            get
            {
                return this._Length1Unit;
            }
            set
            {
                this.OnLength1UnitChanging(value);
                this._Length1Unit = value;
                this.OnLength1UnitChanged();
                this.OnPropertyChanged("Length1Unit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _Length1Unit;
        partial void OnLength1UnitChanging(global::System.Nullable<int> value);
        partial void OnLength1UnitChanged();
        /// <summary>
        /// There are no comments for Property Length2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Length2")]
        public virtual global::System.Nullable<double> Length2
        {
            get
            {
                return this._Length2;
            }
            set
            {
                this.OnLength2Changing(value);
                this._Length2 = value;
                this.OnLength2Changed();
                this.OnPropertyChanged("Length2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _Length2;
        partial void OnLength2Changing(global::System.Nullable<double> value);
        partial void OnLength2Changed();
        /// <summary>
        /// There are no comments for Property Length2Unit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Length2Unit")]
        public virtual global::System.Nullable<int> Length2Unit
        {
            get
            {
                return this._Length2Unit;
            }
            set
            {
                this.OnLength2UnitChanging(value);
                this._Length2Unit = value;
                this.OnLength2UnitChanged();
                this.OnPropertyChanged("Length2Unit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _Length2Unit;
        partial void OnLength2UnitChanging(global::System.Nullable<int> value);
        partial void OnLength2UnitChanged();
        /// <summary>
        /// There are no comments for Property Width1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Width1")]
        public virtual global::System.Nullable<double> Width1
        {
            get
            {
                return this._Width1;
            }
            set
            {
                this.OnWidth1Changing(value);
                this._Width1 = value;
                this.OnWidth1Changed();
                this.OnPropertyChanged("Width1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _Width1;
        partial void OnWidth1Changing(global::System.Nullable<double> value);
        partial void OnWidth1Changed();
        /// <summary>
        /// There are no comments for Property Width1Unit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Width1Unit")]
        public virtual global::System.Nullable<int> Width1Unit
        {
            get
            {
                return this._Width1Unit;
            }
            set
            {
                this.OnWidth1UnitChanging(value);
                this._Width1Unit = value;
                this.OnWidth1UnitChanged();
                this.OnPropertyChanged("Width1Unit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _Width1Unit;
        partial void OnWidth1UnitChanging(global::System.Nullable<int> value);
        partial void OnWidth1UnitChanged();
        /// <summary>
        /// There are no comments for Property Width2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Width2")]
        public virtual global::System.Nullable<double> Width2
        {
            get
            {
                return this._Width2;
            }
            set
            {
                this.OnWidth2Changing(value);
                this._Width2 = value;
                this.OnWidth2Changed();
                this.OnPropertyChanged("Width2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _Width2;
        partial void OnWidth2Changing(global::System.Nullable<double> value);
        partial void OnWidth2Changed();
        /// <summary>
        /// There are no comments for Property Width2Unit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Width2Unit")]
        public virtual global::System.Nullable<int> Width2Unit
        {
            get
            {
                return this._Width2Unit;
            }
            set
            {
                this.OnWidth2UnitChanging(value);
                this._Width2Unit = value;
                this.OnWidth2UnitChanged();
                this.OnPropertyChanged("Width2Unit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _Width2Unit;
        partial void OnWidth2UnitChanging(global::System.Nullable<int> value);
        partial void OnWidth2UnitChanged();
        /// <summary>
        /// There are no comments for Property Height1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Height1")]
        public virtual global::System.Nullable<double> Height1
        {
            get
            {
                return this._Height1;
            }
            set
            {
                this.OnHeight1Changing(value);
                this._Height1 = value;
                this.OnHeight1Changed();
                this.OnPropertyChanged("Height1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _Height1;
        partial void OnHeight1Changing(global::System.Nullable<double> value);
        partial void OnHeight1Changed();
        /// <summary>
        /// There are no comments for Property Height1Unit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Height1Unit")]
        public virtual global::System.Nullable<int> Height1Unit
        {
            get
            {
                return this._Height1Unit;
            }
            set
            {
                this.OnHeight1UnitChanging(value);
                this._Height1Unit = value;
                this.OnHeight1UnitChanged();
                this.OnPropertyChanged("Height1Unit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _Height1Unit;
        partial void OnHeight1UnitChanging(global::System.Nullable<int> value);
        partial void OnHeight1UnitChanged();
        /// <summary>
        /// There are no comments for Property Height2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Height2")]
        public virtual global::System.Nullable<double> Height2
        {
            get
            {
                return this._Height2;
            }
            set
            {
                this.OnHeight2Changing(value);
                this._Height2 = value;
                this.OnHeight2Changed();
                this.OnPropertyChanged("Height2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _Height2;
        partial void OnHeight2Changing(global::System.Nullable<double> value);
        partial void OnHeight2Changed();
        /// <summary>
        /// There are no comments for Property Height2Unit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Height2Unit")]
        public virtual global::System.Nullable<int> Height2Unit
        {
            get
            {
                return this._Height2Unit;
            }
            set
            {
                this.OnHeight2UnitChanging(value);
                this._Height2Unit = value;
                this.OnHeight2UnitChanged();
                this.OnPropertyChanged("Height2Unit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _Height2Unit;
        partial void OnHeight2UnitChanging(global::System.Nullable<int> value);
        partial void OnHeight2UnitChanged();
        /// <summary>
        /// There are no comments for Property Volume in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Volume")]
        public virtual global::System.Nullable<double> Volume
        {
            get
            {
                return this._Volume;
            }
            set
            {
                this.OnVolumeChanging(value);
                this._Volume = value;
                this.OnVolumeChanged();
                this.OnPropertyChanged("Volume");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _Volume;
        partial void OnVolumeChanging(global::System.Nullable<double> value);
        partial void OnVolumeChanged();
        /// <summary>
        /// There are no comments for Property VolumeUnit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("VolumeUnit")]
        public virtual global::System.Nullable<int> VolumeUnit
        {
            get
            {
                return this._VolumeUnit;
            }
            set
            {
                this.OnVolumeUnitChanging(value);
                this._VolumeUnit = value;
                this.OnVolumeUnitChanged();
                this.OnPropertyChanged("VolumeUnit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _VolumeUnit;
        partial void OnVolumeUnitChanging(global::System.Nullable<int> value);
        partial void OnVolumeUnitChanged();
        /// <summary>
        /// There are no comments for Property Weight1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Weight1")]
        public virtual global::System.Nullable<double> Weight1
        {
            get
            {
                return this._Weight1;
            }
            set
            {
                this.OnWeight1Changing(value);
                this._Weight1 = value;
                this.OnWeight1Changed();
                this.OnPropertyChanged("Weight1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _Weight1;
        partial void OnWeight1Changing(global::System.Nullable<double> value);
        partial void OnWeight1Changed();
        /// <summary>
        /// There are no comments for Property Weight1Unit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Weight1Unit")]
        public virtual global::System.Nullable<int> Weight1Unit
        {
            get
            {
                return this._Weight1Unit;
            }
            set
            {
                this.OnWeight1UnitChanging(value);
                this._Weight1Unit = value;
                this.OnWeight1UnitChanged();
                this.OnPropertyChanged("Weight1Unit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _Weight1Unit;
        partial void OnWeight1UnitChanging(global::System.Nullable<int> value);
        partial void OnWeight1UnitChanged();
        /// <summary>
        /// There are no comments for Property Weight2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Weight2")]
        public virtual global::System.Nullable<double> Weight2
        {
            get
            {
                return this._Weight2;
            }
            set
            {
                this.OnWeight2Changing(value);
                this._Weight2 = value;
                this.OnWeight2Changed();
                this.OnPropertyChanged("Weight2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _Weight2;
        partial void OnWeight2Changing(global::System.Nullable<double> value);
        partial void OnWeight2Changed();
        /// <summary>
        /// There are no comments for Property Weight2Unit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Weight2Unit")]
        public virtual global::System.Nullable<int> Weight2Unit
        {
            get
            {
                return this._Weight2Unit;
            }
            set
            {
                this.OnWeight2UnitChanging(value);
                this._Weight2Unit = value;
                this.OnWeight2UnitChanged();
                this.OnPropertyChanged("Weight2Unit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _Weight2Unit;
        partial void OnWeight2UnitChanging(global::System.Nullable<int> value);
        partial void OnWeight2UnitChanged();
        /// <summary>
        /// There are no comments for Property DynamicProperties in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DynamicProperties")]
        public virtual global::System.Collections.Generic.IDictionary<string, object> DynamicProperties
        {
            get
            {
                return this._DynamicProperties;
            }
            set
            {
                this.OnDynamicPropertiesChanging(value);
                this._DynamicProperties = value;
                this.OnDynamicPropertiesChanged();
                this.OnPropertyChanged("DynamicProperties");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.Generic.IDictionary<string, object> _DynamicProperties = new global::System.Collections.Generic.Dictionary<string, object>();
        partial void OnDynamicPropertiesChanging(global::System.Collections.Generic.IDictionary<string, object> value);
        partial void OnDynamicPropertiesChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
