//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2/9/2023 12:16:29 PM
namespace SAPB1
{
    /// <summary>
    /// There are no comments for PM_DocumentData in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("PM_DocumentData")]
    public partial class PM_DocumentData : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property LineID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("LineID")]
        public virtual global::System.Nullable<int> LineID
        {
            get
            {
                return this._LineID;
            }
            set
            {
                this.OnLineIDChanging(value);
                this._LineID = value;
                this.OnLineIDChanged();
                this.OnPropertyChanged("LineID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _LineID;
        partial void OnLineIDChanging(global::System.Nullable<int> value);
        partial void OnLineIDChanged();
        /// <summary>
        /// There are no comments for Property StageID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("StageID")]
        public virtual global::System.Nullable<int> StageID
        {
            get
            {
                return this._StageID;
            }
            set
            {
                this.OnStageIDChanging(value);
                this._StageID = value;
                this.OnStageIDChanged();
                this.OnPropertyChanged("StageID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _StageID;
        partial void OnStageIDChanging(global::System.Nullable<int> value);
        partial void OnStageIDChanged();
        /// <summary>
        /// There are no comments for Property DocType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DocType")]
        public virtual global::System.Nullable<global::SAPB1.PMDocumentTypeEnum> DocType
        {
            get
            {
                return this._DocType;
            }
            set
            {
                this.OnDocTypeChanging(value);
                this._DocType = value;
                this.OnDocTypeChanged();
                this.OnPropertyChanged("DocType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::SAPB1.PMDocumentTypeEnum> _DocType;
        partial void OnDocTypeChanging(global::System.Nullable<global::SAPB1.PMDocumentTypeEnum> value);
        partial void OnDocTypeChanged();
        /// <summary>
        /// There are no comments for Property DocEntry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DocEntry")]
        public virtual global::System.Nullable<int> DocEntry
        {
            get
            {
                return this._DocEntry;
            }
            set
            {
                this.OnDocEntryChanging(value);
                this._DocEntry = value;
                this.OnDocEntryChanged();
                this.OnPropertyChanged("DocEntry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _DocEntry;
        partial void OnDocEntryChanging(global::System.Nullable<int> value);
        partial void OnDocEntryChanged();
        /// <summary>
        /// There are no comments for Property DocDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DocDate")]
        public virtual global::System.Nullable<global::System.DateTimeOffset> DocDate
        {
            get
            {
                return this._DocDate;
            }
            set
            {
                this.OnDocDateChanging(value);
                this._DocDate = value;
                this.OnDocDateChanged();
                this.OnPropertyChanged("DocDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::System.DateTimeOffset> _DocDate;
        partial void OnDocDateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDocDateChanged();
        /// <summary>
        /// There are no comments for Property Total in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Total")]
        public virtual global::System.Nullable<double> Total
        {
            get
            {
                return this._Total;
            }
            set
            {
                this.OnTotalChanging(value);
                this._Total = value;
                this.OnTotalChanged();
                this.OnPropertyChanged("Total");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _Total;
        partial void OnTotalChanging(global::System.Nullable<double> value);
        partial void OnTotalChanged();
        /// <summary>
        /// There are no comments for Property LineNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("LineNumber")]
        public virtual global::System.Nullable<int> LineNumber
        {
            get
            {
                return this._LineNumber;
            }
            set
            {
                this.OnLineNumberChanging(value);
                this._LineNumber = value;
                this.OnLineNumberChanged();
                this.OnPropertyChanged("LineNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _LineNumber;
        partial void OnLineNumberChanging(global::System.Nullable<int> value);
        partial void OnLineNumberChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Status")]
        public virtual global::System.Nullable<global::SAPB1.LineStatusTypeEnum> Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this._Status = value;
                this.OnStatusChanged();
                this.OnPropertyChanged("Status");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::SAPB1.LineStatusTypeEnum> _Status;
        partial void OnStatusChanging(global::System.Nullable<global::SAPB1.LineStatusTypeEnum> value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property AmountCategory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AmountCategory")]
        public virtual global::System.Nullable<global::SAPB1.AmountCatTypeEnum> AmountCategory
        {
            get
            {
                return this._AmountCategory;
            }
            set
            {
                this.OnAmountCategoryChanging(value);
                this._AmountCategory = value;
                this.OnAmountCategoryChanged();
                this.OnPropertyChanged("AmountCategory");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::SAPB1.AmountCatTypeEnum> _AmountCategory;
        partial void OnAmountCategoryChanging(global::System.Nullable<global::SAPB1.AmountCatTypeEnum> value);
        partial void OnAmountCategoryChanged();
        /// <summary>
        /// There are no comments for Property Categorize in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Categorize")]
        public virtual global::System.Nullable<global::SAPB1.PMCategorizeTypeEnum> Categorize
        {
            get
            {
                return this._Categorize;
            }
            set
            {
                this.OnCategorizeChanging(value);
                this._Categorize = value;
                this.OnCategorizeChanged();
                this.OnPropertyChanged("Categorize");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::SAPB1.PMCategorizeTypeEnum> _Categorize;
        partial void OnCategorizeChanging(global::System.Nullable<global::SAPB1.PMCategorizeTypeEnum> value);
        partial void OnCategorizeChanged();
        /// <summary>
        /// There are no comments for Property Operation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Operation")]
        public virtual global::System.Nullable<global::SAPB1.PMOperationTypeEnum> Operation
        {
            get
            {
                return this._Operation;
            }
            set
            {
                this.OnOperationChanging(value);
                this._Operation = value;
                this.OnOperationChanged();
                this.OnPropertyChanged("Operation");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::SAPB1.PMOperationTypeEnum> _Operation;
        partial void OnOperationChanging(global::System.Nullable<global::SAPB1.PMOperationTypeEnum> value);
        partial void OnOperationChanged();
        /// <summary>
        /// There are no comments for Property DynamicProperties in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DynamicProperties")]
        public virtual global::System.Collections.Generic.IDictionary<string, object> DynamicProperties
        {
            get
            {
                return this._DynamicProperties;
            }
            set
            {
                this.OnDynamicPropertiesChanging(value);
                this._DynamicProperties = value;
                this.OnDynamicPropertiesChanged();
                this.OnPropertyChanged("DynamicProperties");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.Generic.IDictionary<string, object> _DynamicProperties = new global::System.Collections.Generic.Dictionary<string, object>();
        partial void OnDynamicPropertiesChanging(global::System.Collections.Generic.IDictionary<string, object> value);
        partial void OnDynamicPropertiesChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
