//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2/9/2023 12:16:29 PM
namespace SAPB1
{
    /// <summary>
    /// There are no comments for ReportLayout in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ReportLayout")]
    public partial class ReportLayout : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Author in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Author")]
        public virtual string Author
        {
            get
            {
                return this._Author;
            }
            set
            {
                this.OnAuthorChanging(value);
                this._Author = value;
                this.OnAuthorChanged();
                this.OnPropertyChanged("Author");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Author;
        partial void OnAuthorChanging(string value);
        partial void OnAuthorChanged();
        /// <summary>
        /// There are no comments for Property Remarks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Remarks")]
        public virtual string Remarks
        {
            get
            {
                return this._Remarks;
            }
            set
            {
                this.OnRemarksChanging(value);
                this._Remarks = value;
                this.OnRemarksChanged();
                this.OnPropertyChanged("Remarks");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Remarks;
        partial void OnRemarksChanging(string value);
        partial void OnRemarksChanged();
        /// <summary>
        /// There are no comments for Property Width in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Width")]
        public virtual global::System.Nullable<int> Width
        {
            get
            {
                return this._Width;
            }
            set
            {
                this.OnWidthChanging(value);
                this._Width = value;
                this.OnWidthChanged();
                this.OnPropertyChanged("Width");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _Width;
        partial void OnWidthChanging(global::System.Nullable<int> value);
        partial void OnWidthChanged();
        /// <summary>
        /// There are no comments for Property Height in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Height")]
        public virtual global::System.Nullable<int> Height
        {
            get
            {
                return this._Height;
            }
            set
            {
                this.OnHeightChanging(value);
                this._Height = value;
                this.OnHeightChanged();
                this.OnPropertyChanged("Height");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _Height;
        partial void OnHeightChanging(global::System.Nullable<int> value);
        partial void OnHeightChanged();
        /// <summary>
        /// There are no comments for Property LeftMargin in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("LeftMargin")]
        public virtual global::System.Nullable<int> LeftMargin
        {
            get
            {
                return this._LeftMargin;
            }
            set
            {
                this.OnLeftMarginChanging(value);
                this._LeftMargin = value;
                this.OnLeftMarginChanged();
                this.OnPropertyChanged("LeftMargin");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _LeftMargin;
        partial void OnLeftMarginChanging(global::System.Nullable<int> value);
        partial void OnLeftMarginChanged();
        /// <summary>
        /// There are no comments for Property RightMargin in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("RightMargin")]
        public virtual global::System.Nullable<int> RightMargin
        {
            get
            {
                return this._RightMargin;
            }
            set
            {
                this.OnRightMarginChanging(value);
                this._RightMargin = value;
                this.OnRightMarginChanged();
                this.OnPropertyChanged("RightMargin");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _RightMargin;
        partial void OnRightMarginChanging(global::System.Nullable<int> value);
        partial void OnRightMarginChanged();
        /// <summary>
        /// There are no comments for Property TopMargin in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TopMargin")]
        public virtual global::System.Nullable<int> TopMargin
        {
            get
            {
                return this._TopMargin;
            }
            set
            {
                this.OnTopMarginChanging(value);
                this._TopMargin = value;
                this.OnTopMarginChanged();
                this.OnPropertyChanged("TopMargin");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _TopMargin;
        partial void OnTopMarginChanging(global::System.Nullable<int> value);
        partial void OnTopMarginChanged();
        /// <summary>
        /// There are no comments for Property BottomMargin in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BottomMargin")]
        public virtual global::System.Nullable<int> BottomMargin
        {
            get
            {
                return this._BottomMargin;
            }
            set
            {
                this.OnBottomMarginChanging(value);
                this._BottomMargin = value;
                this.OnBottomMarginChanged();
                this.OnPropertyChanged("BottomMargin");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _BottomMargin;
        partial void OnBottomMarginChanging(global::System.Nullable<int> value);
        partial void OnBottomMarginChanged();
        /// <summary>
        /// There are no comments for Property Editable in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Editable")]
        public virtual global::System.Nullable<global::SAPB1.BoYesNoEnum> Editable
        {
            get
            {
                return this._Editable;
            }
            set
            {
                this.OnEditableChanging(value);
                this._Editable = value;
                this.OnEditableChanged();
                this.OnPropertyChanged("Editable");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::SAPB1.BoYesNoEnum> _Editable;
        partial void OnEditableChanging(global::System.Nullable<global::SAPB1.BoYesNoEnum> value);
        partial void OnEditableChanged();
        /// <summary>
        /// There are no comments for Property PaperSize in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PaperSize")]
        public virtual string PaperSize
        {
            get
            {
                return this._PaperSize;
            }
            set
            {
                this.OnPaperSizeChanging(value);
                this._PaperSize = value;
                this.OnPaperSizeChanged();
                this.OnPropertyChanged("PaperSize");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _PaperSize;
        partial void OnPaperSizeChanging(string value);
        partial void OnPaperSizeChanged();
        /// <summary>
        /// There are no comments for Property Orientation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Orientation")]
        public virtual global::System.Nullable<global::SAPB1.BoOrientationEnum> Orientation
        {
            get
            {
                return this._Orientation;
            }
            set
            {
                this.OnOrientationChanging(value);
                this._Orientation = value;
                this.OnOrientationChanged();
                this.OnPropertyChanged("Orientation");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::SAPB1.BoOrientationEnum> _Orientation;
        partial void OnOrientationChanging(global::System.Nullable<global::SAPB1.BoOrientationEnum> value);
        partial void OnOrientationChanged();
        /// <summary>
        /// There are no comments for Property GridSize in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("GridSize")]
        public virtual global::System.Nullable<int> GridSize
        {
            get
            {
                return this._GridSize;
            }
            set
            {
                this.OnGridSizeChanging(value);
                this._GridSize = value;
                this.OnGridSizeChanged();
                this.OnPropertyChanged("GridSize");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _GridSize;
        partial void OnGridSizeChanging(global::System.Nullable<int> value);
        partial void OnGridSizeChanged();
        /// <summary>
        /// There are no comments for Property GridType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("GridType")]
        public virtual global::System.Nullable<global::SAPB1.BoGridTypeEnum> GridType
        {
            get
            {
                return this._GridType;
            }
            set
            {
                this.OnGridTypeChanging(value);
                this._GridType = value;
                this.OnGridTypeChanged();
                this.OnPropertyChanged("GridType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::SAPB1.BoGridTypeEnum> _GridType;
        partial void OnGridTypeChanging(global::System.Nullable<global::SAPB1.BoGridTypeEnum> value);
        partial void OnGridTypeChanged();
        /// <summary>
        /// There are no comments for Property ShowGrid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ShowGrid")]
        public virtual global::System.Nullable<global::SAPB1.BoYesNoEnum> ShowGrid
        {
            get
            {
                return this._ShowGrid;
            }
            set
            {
                this.OnShowGridChanging(value);
                this._ShowGrid = value;
                this.OnShowGridChanged();
                this.OnPropertyChanged("ShowGrid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::SAPB1.BoYesNoEnum> _ShowGrid;
        partial void OnShowGridChanging(global::System.Nullable<global::SAPB1.BoYesNoEnum> value);
        partial void OnShowGridChanged();
        /// <summary>
        /// There are no comments for Property SnapToGrid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("SnapToGrid")]
        public virtual global::System.Nullable<global::SAPB1.BoYesNoEnum> SnapToGrid
        {
            get
            {
                return this._SnapToGrid;
            }
            set
            {
                this.OnSnapToGridChanging(value);
                this._SnapToGrid = value;
                this.OnSnapToGridChanged();
                this.OnPropertyChanged("SnapToGrid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::SAPB1.BoYesNoEnum> _SnapToGrid;
        partial void OnSnapToGridChanging(global::System.Nullable<global::SAPB1.BoYesNoEnum> value);
        partial void OnSnapToGridChanged();
        /// <summary>
        /// There are no comments for Property Picture in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Picture")]
        public virtual string Picture
        {
            get
            {
                return this._Picture;
            }
            set
            {
                this.OnPictureChanging(value);
                this._Picture = value;
                this.OnPictureChanged();
                this.OnPropertyChanged("Picture");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Picture;
        partial void OnPictureChanging(string value);
        partial void OnPictureChanged();
        /// <summary>
        /// There are no comments for Property TypeCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TypeCode")]
        public virtual string TypeCode
        {
            get
            {
                return this._TypeCode;
            }
            set
            {
                this.OnTypeCodeChanging(value);
                this._TypeCode = value;
                this.OnTypeCodeChanged();
                this.OnPropertyChanged("TypeCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _TypeCode;
        partial void OnTypeCodeChanging(string value);
        partial void OnTypeCodeChanged();
        /// <summary>
        /// There are no comments for Property ForeignLanguageReport in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ForeignLanguageReport")]
        public virtual global::System.Nullable<global::SAPB1.BoYesNoEnum> ForeignLanguageReport
        {
            get
            {
                return this._ForeignLanguageReport;
            }
            set
            {
                this.OnForeignLanguageReportChanging(value);
                this._ForeignLanguageReport = value;
                this.OnForeignLanguageReportChanged();
                this.OnPropertyChanged("ForeignLanguageReport");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::SAPB1.BoYesNoEnum> _ForeignLanguageReport;
        partial void OnForeignLanguageReportChanging(global::System.Nullable<global::SAPB1.BoYesNoEnum> value);
        partial void OnForeignLanguageReportChanged();
        /// <summary>
        /// There are no comments for Property Sortable in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Sortable")]
        public virtual global::System.Nullable<global::SAPB1.BoYesNoEnum> Sortable
        {
            get
            {
                return this._Sortable;
            }
            set
            {
                this.OnSortableChanging(value);
                this._Sortable = value;
                this.OnSortableChanged();
                this.OnPropertyChanged("Sortable");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::SAPB1.BoYesNoEnum> _Sortable;
        partial void OnSortableChanging(global::System.Nullable<global::SAPB1.BoYesNoEnum> value);
        partial void OnSortableChanged();
        /// <summary>
        /// There are no comments for Property LeaderReport in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("LeaderReport")]
        public virtual string LeaderReport
        {
            get
            {
                return this._LeaderReport;
            }
            set
            {
                this.OnLeaderReportChanging(value);
                this._LeaderReport = value;
                this.OnLeaderReportChanged();
                this.OnPropertyChanged("LeaderReport");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _LeaderReport;
        partial void OnLeaderReportChanging(string value);
        partial void OnLeaderReportChanged();
        /// <summary>
        /// There are no comments for Property FollowUpReport in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("FollowUpReport")]
        public virtual string FollowUpReport
        {
            get
            {
                return this._FollowUpReport;
            }
            set
            {
                this.OnFollowUpReportChanging(value);
                this._FollowUpReport = value;
                this.OnFollowUpReportChanged();
                this.OnPropertyChanged("FollowUpReport");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _FollowUpReport;
        partial void OnFollowUpReportChanging(string value);
        partial void OnFollowUpReportChanged();
        /// <summary>
        /// There are no comments for Property ConvertFontInPrintPreview in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ConvertFontInPrintPreview")]
        public virtual global::System.Nullable<global::SAPB1.BoYesNoEnum> ConvertFontInPrintPreview
        {
            get
            {
                return this._ConvertFontInPrintPreview;
            }
            set
            {
                this.OnConvertFontInPrintPreviewChanging(value);
                this._ConvertFontInPrintPreview = value;
                this.OnConvertFontInPrintPreviewChanged();
                this.OnPropertyChanged("ConvertFontInPrintPreview");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::SAPB1.BoYesNoEnum> _ConvertFontInPrintPreview;
        partial void OnConvertFontInPrintPreviewChanging(global::System.Nullable<global::SAPB1.BoYesNoEnum> value);
        partial void OnConvertFontInPrintPreviewChanged();
        /// <summary>
        /// There are no comments for Property PreviewPrintingFont in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PreviewPrintingFont")]
        public virtual string PreviewPrintingFont
        {
            get
            {
                return this._PreviewPrintingFont;
            }
            set
            {
                this.OnPreviewPrintingFontChanging(value);
                this._PreviewPrintingFont = value;
                this.OnPreviewPrintingFontChanged();
                this.OnPropertyChanged("PreviewPrintingFont");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _PreviewPrintingFont;
        partial void OnPreviewPrintingFontChanging(string value);
        partial void OnPreviewPrintingFontChanged();
        /// <summary>
        /// There are no comments for Property ChangeFontSizeInPreview in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ChangeFontSizeInPreview")]
        public virtual global::System.Nullable<int> ChangeFontSizeInPreview
        {
            get
            {
                return this._ChangeFontSizeInPreview;
            }
            set
            {
                this.OnChangeFontSizeInPreviewChanging(value);
                this._ChangeFontSizeInPreview = value;
                this.OnChangeFontSizeInPreviewChanged();
                this.OnPropertyChanged("ChangeFontSizeInPreview");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _ChangeFontSizeInPreview;
        partial void OnChangeFontSizeInPreviewChanging(global::System.Nullable<int> value);
        partial void OnChangeFontSizeInPreviewChanged();
        /// <summary>
        /// There are no comments for Property ConvertFontForEMail in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ConvertFontForEMail")]
        public virtual global::System.Nullable<global::SAPB1.BoYesNoEnum> ConvertFontForEMail
        {
            get
            {
                return this._ConvertFontForEMail;
            }
            set
            {
                this.OnConvertFontForEMailChanging(value);
                this._ConvertFontForEMail = value;
                this.OnConvertFontForEMailChanged();
                this.OnPropertyChanged("ConvertFontForEMail");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::SAPB1.BoYesNoEnum> _ConvertFontForEMail;
        partial void OnConvertFontForEMailChanging(global::System.Nullable<global::SAPB1.BoYesNoEnum> value);
        partial void OnConvertFontForEMailChanged();
        /// <summary>
        /// There are no comments for Property EMailFont in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("EMailFont")]
        public virtual string EMailFont
        {
            get
            {
                return this._EMailFont;
            }
            set
            {
                this.OnEMailFontChanging(value);
                this._EMailFont = value;
                this.OnEMailFontChanged();
                this.OnPropertyChanged("EMailFont");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _EMailFont;
        partial void OnEMailFontChanging(string value);
        partial void OnEMailFontChanged();
        /// <summary>
        /// There are no comments for Property ChangeFontSizeForEMail in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ChangeFontSizeForEMail")]
        public virtual global::System.Nullable<int> ChangeFontSizeForEMail
        {
            get
            {
                return this._ChangeFontSizeForEMail;
            }
            set
            {
                this.OnChangeFontSizeForEMailChanging(value);
                this._ChangeFontSizeForEMail = value;
                this.OnChangeFontSizeForEMailChanged();
                this.OnPropertyChanged("ChangeFontSizeForEMail");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _ChangeFontSizeForEMail;
        partial void OnChangeFontSizeForEMailChanging(global::System.Nullable<int> value);
        partial void OnChangeFontSizeForEMailChanged();
        /// <summary>
        /// There are no comments for Property Query in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Query")]
        public virtual string Query
        {
            get
            {
                return this._Query;
            }
            set
            {
                this.OnQueryChanging(value);
                this._Query = value;
                this.OnQueryChanged();
                this.OnPropertyChanged("Query");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Query;
        partial void OnQueryChanging(string value);
        partial void OnQueryChanged();
        /// <summary>
        /// There are no comments for Property QueryType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("QueryType")]
        public virtual global::System.Nullable<global::SAPB1.BoQueryTypeEnum> QueryType
        {
            get
            {
                return this._QueryType;
            }
            set
            {
                this.OnQueryTypeChanging(value);
                this._QueryType = value;
                this.OnQueryTypeChanged();
                this.OnPropertyChanged("QueryType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::SAPB1.BoQueryTypeEnum> _QueryType;
        partial void OnQueryTypeChanging(global::System.Nullable<global::SAPB1.BoQueryTypeEnum> value);
        partial void OnQueryTypeChanged();
        /// <summary>
        /// There are no comments for Property Language in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("language")]
        public virtual global::System.Nullable<int> Language
        {
            get
            {
                return this._Language;
            }
            set
            {
                this.OnLanguageChanging(value);
                this._Language = value;
                this.OnLanguageChanged();
                this.OnPropertyChanged("language");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _Language;
        partial void OnLanguageChanging(global::System.Nullable<int> value);
        partial void OnLanguageChanged();
        /// <summary>
        /// There are no comments for Property ImpExpObjCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ImpExpObjCode")]
        public virtual global::System.Nullable<int> ImpExpObjCode
        {
            get
            {
                return this._ImpExpObjCode;
            }
            set
            {
                this.OnImpExpObjCodeChanging(value);
                this._ImpExpObjCode = value;
                this.OnImpExpObjCodeChanged();
                this.OnPropertyChanged("ImpExpObjCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _ImpExpObjCode;
        partial void OnImpExpObjCodeChanging(global::System.Nullable<int> value);
        partial void OnImpExpObjCodeChanged();
        /// <summary>
        /// There are no comments for Property ExtensionName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ExtensionName")]
        public virtual string ExtensionName
        {
            get
            {
                return this._ExtensionName;
            }
            set
            {
                this.OnExtensionNameChanging(value);
                this._ExtensionName = value;
                this.OnExtensionNameChanged();
                this.OnPropertyChanged("ExtensionName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ExtensionName;
        partial void OnExtensionNameChanging(string value);
        partial void OnExtensionNameChanged();
        /// <summary>
        /// There are no comments for Property ExtensionErrorAction in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ExtensionErrorAction")]
        public virtual global::System.Nullable<global::SAPB1.BoExtensionErrorActionEnum> ExtensionErrorAction
        {
            get
            {
                return this._ExtensionErrorAction;
            }
            set
            {
                this.OnExtensionErrorActionChanging(value);
                this._ExtensionErrorAction = value;
                this.OnExtensionErrorActionChanged();
                this.OnPropertyChanged("ExtensionErrorAction");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::SAPB1.BoExtensionErrorActionEnum> _ExtensionErrorAction;
        partial void OnExtensionErrorActionChanging(global::System.Nullable<global::SAPB1.BoExtensionErrorActionEnum> value);
        partial void OnExtensionErrorActionChanged();
        /// <summary>
        /// There are no comments for Property RepetitiveAreasNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("RepetitiveAreasNumber")]
        public virtual global::System.Nullable<int> RepetitiveAreasNumber
        {
            get
            {
                return this._RepetitiveAreasNumber;
            }
            set
            {
                this.OnRepetitiveAreasNumberChanging(value);
                this._RepetitiveAreasNumber = value;
                this.OnRepetitiveAreasNumberChanged();
                this.OnPropertyChanged("RepetitiveAreasNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _RepetitiveAreasNumber;
        partial void OnRepetitiveAreasNumberChanging(global::System.Nullable<int> value);
        partial void OnRepetitiveAreasNumberChanged();
        /// <summary>
        /// There are no comments for Property AllignFooterToBottom in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AllignFooterToBottom")]
        public virtual global::System.Nullable<global::SAPB1.BoYesNoEnum> AllignFooterToBottom
        {
            get
            {
                return this._AllignFooterToBottom;
            }
            set
            {
                this.OnAllignFooterToBottomChanging(value);
                this._AllignFooterToBottom = value;
                this.OnAllignFooterToBottomChanged();
                this.OnPropertyChanged("AllignFooterToBottom");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::SAPB1.BoYesNoEnum> _AllignFooterToBottom;
        partial void OnAllignFooterToBottomChanging(global::System.Nullable<global::SAPB1.BoYesNoEnum> value);
        partial void OnAllignFooterToBottomChanged();
        /// <summary>
        /// There are no comments for Property LayoutCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("LayoutCode")]
        public virtual string LayoutCode
        {
            get
            {
                return this._LayoutCode;
            }
            set
            {
                this.OnLayoutCodeChanging(value);
                this._LayoutCode = value;
                this.OnLayoutCodeChanged();
                this.OnPropertyChanged("LayoutCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _LayoutCode;
        partial void OnLayoutCodeChanging(string value);
        partial void OnLayoutCodeChanged();
        /// <summary>
        /// There are no comments for Property Category in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Category")]
        public virtual global::System.Nullable<global::SAPB1.ReportLayoutCategoryEnum> Category
        {
            get
            {
                return this._Category;
            }
            set
            {
                this.OnCategoryChanging(value);
                this._Category = value;
                this.OnCategoryChanged();
                this.OnPropertyChanged("Category");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::SAPB1.ReportLayoutCategoryEnum> _Category;
        partial void OnCategoryChanging(global::System.Nullable<global::SAPB1.ReportLayoutCategoryEnum> value);
        partial void OnCategoryChanged();
        /// <summary>
        /// There are no comments for Property Printer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Printer")]
        public virtual string Printer
        {
            get
            {
                return this._Printer;
            }
            set
            {
                this.OnPrinterChanging(value);
                this._Printer = value;
                this.OnPrinterChanged();
                this.OnPropertyChanged("Printer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Printer;
        partial void OnPrinterChanging(string value);
        partial void OnPrinterChanged();
        /// <summary>
        /// There are no comments for Property PrinterFirstPage in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PrinterFirstPage")]
        public virtual string PrinterFirstPage
        {
            get
            {
                return this._PrinterFirstPage;
            }
            set
            {
                this.OnPrinterFirstPageChanging(value);
                this._PrinterFirstPage = value;
                this.OnPrinterFirstPageChanged();
                this.OnPropertyChanged("PrinterFirstPage");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _PrinterFirstPage;
        partial void OnPrinterFirstPageChanging(string value);
        partial void OnPrinterFirstPageChanged();
        /// <summary>
        /// There are no comments for Property NumberOfCopies in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("NumberOfCopies")]
        public virtual global::System.Nullable<int> NumberOfCopies
        {
            get
            {
                return this._NumberOfCopies;
            }
            set
            {
                this.OnNumberOfCopiesChanging(value);
                this._NumberOfCopies = value;
                this.OnNumberOfCopiesChanged();
                this.OnPropertyChanged("NumberOfCopies");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _NumberOfCopies;
        partial void OnNumberOfCopiesChanging(global::System.Nullable<int> value);
        partial void OnNumberOfCopiesChanged();
        /// <summary>
        /// There are no comments for Property Localization in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Localization")]
        public virtual string Localization
        {
            get
            {
                return this._Localization;
            }
            set
            {
                this.OnLocalizationChanging(value);
                this._Localization = value;
                this.OnLocalizationChanged();
                this.OnPropertyChanged("Localization");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Localization;
        partial void OnLocalizationChanging(string value);
        partial void OnLocalizationChanged();
        /// <summary>
        /// There are no comments for Property UseFirstPrinter in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("UseFirstPrinter")]
        public virtual global::System.Nullable<global::SAPB1.BoYesNoEnum> UseFirstPrinter
        {
            get
            {
                return this._UseFirstPrinter;
            }
            set
            {
                this.OnUseFirstPrinterChanging(value);
                this._UseFirstPrinter = value;
                this.OnUseFirstPrinterChanged();
                this.OnPropertyChanged("UseFirstPrinter");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::SAPB1.BoYesNoEnum> _UseFirstPrinter;
        partial void OnUseFirstPrinterChanging(global::System.Nullable<global::SAPB1.BoYesNoEnum> value);
        partial void OnUseFirstPrinterChanged();
        /// <summary>
        /// There are no comments for Property B1Version in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("B1Version")]
        public virtual string B1Version
        {
            get
            {
                return this._B1Version;
            }
            set
            {
                this.OnB1VersionChanging(value);
                this._B1Version = value;
                this.OnB1VersionChanged();
                this.OnPropertyChanged("B1Version");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _B1Version;
        partial void OnB1VersionChanging(string value);
        partial void OnB1VersionChanged();
        /// <summary>
        /// There are no comments for Property CRVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CRVersion")]
        public virtual string CRVersion
        {
            get
            {
                return this._CRVersion;
            }
            set
            {
                this.OnCRVersionChanging(value);
                this._CRVersion = value;
                this.OnCRVersionChanged();
                this.OnPropertyChanged("CRVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _CRVersion;
        partial void OnCRVersionChanging(string value);
        partial void OnCRVersionChanged();
        /// <summary>
        /// There are no comments for Property TypeDetail in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TypeDetail")]
        public virtual string TypeDetail
        {
            get
            {
                return this._TypeDetail;
            }
            set
            {
                this.OnTypeDetailChanging(value);
                this._TypeDetail = value;
                this.OnTypeDetailChanged();
                this.OnPropertyChanged("TypeDetail");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _TypeDetail;
        partial void OnTypeDetailChanging(string value);
        partial void OnTypeDetailChanged();
        /// <summary>
        /// There are no comments for Property ReportLayoutItems in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ReportLayoutItems")]
        public virtual global::System.Collections.ObjectModel.ObservableCollection<global::SAPB1.ReportLayoutItem> ReportLayoutItems
        {
            get
            {
                return this._ReportLayoutItems;
            }
            set
            {
                this.OnReportLayoutItemsChanging(value);
                this._ReportLayoutItems = value;
                this.OnReportLayoutItemsChanged();
                this.OnPropertyChanged("ReportLayoutItems");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.ObservableCollection<global::SAPB1.ReportLayoutItem> _ReportLayoutItems = new global::System.Collections.ObjectModel.ObservableCollection<global::SAPB1.ReportLayoutItem>();
        partial void OnReportLayoutItemsChanging(global::System.Collections.ObjectModel.ObservableCollection<global::SAPB1.ReportLayoutItem> value);
        partial void OnReportLayoutItemsChanged();
        /// <summary>
        /// There are no comments for Property ReportLayout_TranslationLines in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ReportLayout_TranslationLines")]
        public virtual global::System.Collections.ObjectModel.ObservableCollection<global::SAPB1.ReportLayout_TranslationLine> ReportLayout_TranslationLines
        {
            get
            {
                return this._ReportLayout_TranslationLines;
            }
            set
            {
                this.OnReportLayout_TranslationLinesChanging(value);
                this._ReportLayout_TranslationLines = value;
                this.OnReportLayout_TranslationLinesChanged();
                this.OnPropertyChanged("ReportLayout_TranslationLines");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.ObjectModel.ObservableCollection<global::SAPB1.ReportLayout_TranslationLine> _ReportLayout_TranslationLines = new global::System.Collections.ObjectModel.ObservableCollection<global::SAPB1.ReportLayout_TranslationLine>();
        partial void OnReportLayout_TranslationLinesChanging(global::System.Collections.ObjectModel.ObservableCollection<global::SAPB1.ReportLayout_TranslationLine> value);
        partial void OnReportLayout_TranslationLinesChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
