//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2/9/2023 12:16:29 PM
namespace SAPB1
{
    /// <summary>
    /// There are no comments for ReportTypeParams in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ReportTypeParams")]
    public partial class ReportTypeParams : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property TypeCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TypeCode")]
        public virtual string TypeCode
        {
            get
            {
                return this._TypeCode;
            }
            set
            {
                this.OnTypeCodeChanging(value);
                this._TypeCode = value;
                this.OnTypeCodeChanged();
                this.OnPropertyChanged("TypeCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _TypeCode;
        partial void OnTypeCodeChanging(string value);
        partial void OnTypeCodeChanged();
        /// <summary>
        /// There are no comments for Property TypeName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TypeName")]
        public virtual string TypeName
        {
            get
            {
                return this._TypeName;
            }
            set
            {
                this.OnTypeNameChanging(value);
                this._TypeName = value;
                this.OnTypeNameChanged();
                this.OnPropertyChanged("TypeName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _TypeName;
        partial void OnTypeNameChanging(string value);
        partial void OnTypeNameChanged();
        /// <summary>
        /// There are no comments for Property AddonName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AddonName")]
        public virtual string AddonName
        {
            get
            {
                return this._AddonName;
            }
            set
            {
                this.OnAddonNameChanging(value);
                this._AddonName = value;
                this.OnAddonNameChanged();
                this.OnPropertyChanged("AddonName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _AddonName;
        partial void OnAddonNameChanging(string value);
        partial void OnAddonNameChanged();
        /// <summary>
        /// There are no comments for Property AddonFormType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AddonFormType")]
        public virtual string AddonFormType
        {
            get
            {
                return this._AddonFormType;
            }
            set
            {
                this.OnAddonFormTypeChanging(value);
                this._AddonFormType = value;
                this.OnAddonFormTypeChanged();
                this.OnPropertyChanged("AddonFormType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _AddonFormType;
        partial void OnAddonFormTypeChanging(string value);
        partial void OnAddonFormTypeChanged();
        /// <summary>
        /// There are no comments for Property MenuID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("MenuID")]
        public virtual string MenuID
        {
            get
            {
                return this._MenuID;
            }
            set
            {
                this.OnMenuIDChanging(value);
                this._MenuID = value;
                this.OnMenuIDChanged();
                this.OnPropertyChanged("MenuID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _MenuID;
        partial void OnMenuIDChanging(string value);
        partial void OnMenuIDChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
