//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2/9/2023 12:16:29 PM
namespace SAPB1
{
    /// <summary>
    /// There are no comments for ResourceCapacityOwningTypeEnum in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("ResourceCapacityOwningTypeEnum")]
    public enum ResourceCapacityOwningTypeEnum
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("rcotNone")]
        RcotNone = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("rcotProductionOrder")]
        RcotProductionOrder = 202,
        [global::Microsoft.OData.Client.OriginalNameAttribute("rcotIssueForProduction")]
        RcotIssueForProduction = 60,
        [global::Microsoft.OData.Client.OriginalNameAttribute("rcotReceiptFromProduction")]
        RcotReceiptFromProduction = 59
    }
}
