//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2/9/2023 12:16:29 PM
namespace SAPB1
{
    /// <summary>
    /// There are no comments for Series in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Series")]
    public partial class Series : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property Document in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Document")]
        public virtual string Document
        {
            get
            {
                return this._Document;
            }
            set
            {
                this.OnDocumentChanging(value);
                this._Document = value;
                this.OnDocumentChanged();
                this.OnPropertyChanged("Document");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Document;
        partial void OnDocumentChanging(string value);
        partial void OnDocumentChanged();
        /// <summary>
        /// There are no comments for Property DocumentSubType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DocumentSubType")]
        public virtual string DocumentSubType
        {
            get
            {
                return this._DocumentSubType;
            }
            set
            {
                this.OnDocumentSubTypeChanging(value);
                this._DocumentSubType = value;
                this.OnDocumentSubTypeChanged();
                this.OnPropertyChanged("DocumentSubType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _DocumentSubType;
        partial void OnDocumentSubTypeChanging(string value);
        partial void OnDocumentSubTypeChanged();
        /// <summary>
        /// There are no comments for Property InitialNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("InitialNumber")]
        public virtual global::System.Nullable<int> InitialNumber
        {
            get
            {
                return this._InitialNumber;
            }
            set
            {
                this.OnInitialNumberChanging(value);
                this._InitialNumber = value;
                this.OnInitialNumberChanged();
                this.OnPropertyChanged("InitialNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _InitialNumber;
        partial void OnInitialNumberChanging(global::System.Nullable<int> value);
        partial void OnInitialNumberChanged();
        /// <summary>
        /// There are no comments for Property LastNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("LastNumber")]
        public virtual global::System.Nullable<int> LastNumber
        {
            get
            {
                return this._LastNumber;
            }
            set
            {
                this.OnLastNumberChanging(value);
                this._LastNumber = value;
                this.OnLastNumberChanged();
                this.OnPropertyChanged("LastNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _LastNumber;
        partial void OnLastNumberChanging(global::System.Nullable<int> value);
        partial void OnLastNumberChanged();
        /// <summary>
        /// There are no comments for Property NextNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("NextNumber")]
        public virtual global::System.Nullable<int> NextNumber
        {
            get
            {
                return this._NextNumber;
            }
            set
            {
                this.OnNextNumberChanging(value);
                this._NextNumber = value;
                this.OnNextNumberChanged();
                this.OnPropertyChanged("NextNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _NextNumber;
        partial void OnNextNumberChanging(global::System.Nullable<int> value);
        partial void OnNextNumberChanged();
        /// <summary>
        /// There are no comments for Property Prefix in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Prefix")]
        public virtual string Prefix
        {
            get
            {
                return this._Prefix;
            }
            set
            {
                this.OnPrefixChanging(value);
                this._Prefix = value;
                this.OnPrefixChanged();
                this.OnPropertyChanged("Prefix");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Prefix;
        partial void OnPrefixChanging(string value);
        partial void OnPrefixChanged();
        /// <summary>
        /// There are no comments for Property Suffix in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Suffix")]
        public virtual string Suffix
        {
            get
            {
                return this._Suffix;
            }
            set
            {
                this.OnSuffixChanging(value);
                this._Suffix = value;
                this.OnSuffixChanged();
                this.OnPropertyChanged("Suffix");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Suffix;
        partial void OnSuffixChanging(string value);
        partial void OnSuffixChanged();
        /// <summary>
        /// There are no comments for Property Remarks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Remarks")]
        public virtual string Remarks
        {
            get
            {
                return this._Remarks;
            }
            set
            {
                this.OnRemarksChanging(value);
                this._Remarks = value;
                this.OnRemarksChanged();
                this.OnPropertyChanged("Remarks");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Remarks;
        partial void OnRemarksChanging(string value);
        partial void OnRemarksChanged();
        /// <summary>
        /// There are no comments for Property GroupCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("GroupCode")]
        public virtual global::System.Nullable<global::SAPB1.BoSeriesGroupEnum> GroupCode
        {
            get
            {
                return this._GroupCode;
            }
            set
            {
                this.OnGroupCodeChanging(value);
                this._GroupCode = value;
                this.OnGroupCodeChanged();
                this.OnPropertyChanged("GroupCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::SAPB1.BoSeriesGroupEnum> _GroupCode;
        partial void OnGroupCodeChanging(global::System.Nullable<global::SAPB1.BoSeriesGroupEnum> value);
        partial void OnGroupCodeChanged();
        /// <summary>
        /// There are no comments for Property Locked in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Locked")]
        public virtual global::System.Nullable<global::SAPB1.BoYesNoEnum> Locked
        {
            get
            {
                return this._Locked;
            }
            set
            {
                this.OnLockedChanging(value);
                this._Locked = value;
                this.OnLockedChanged();
                this.OnPropertyChanged("Locked");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::SAPB1.BoYesNoEnum> _Locked;
        partial void OnLockedChanging(global::System.Nullable<global::SAPB1.BoYesNoEnum> value);
        partial void OnLockedChanged();
        /// <summary>
        /// There are no comments for Property PeriodIndicator in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PeriodIndicator")]
        public virtual string PeriodIndicator
        {
            get
            {
                return this._PeriodIndicator;
            }
            set
            {
                this.OnPeriodIndicatorChanging(value);
                this._PeriodIndicator = value;
                this.OnPeriodIndicatorChanged();
                this.OnPropertyChanged("PeriodIndicator");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _PeriodIndicator;
        partial void OnPeriodIndicatorChanging(string value);
        partial void OnPeriodIndicatorChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public virtual string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property SeriesProperty in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("SeriesProperty")]
        public virtual global::System.Nullable<int> SeriesProperty
        {
            get
            {
                return this._SeriesProperty;
            }
            set
            {
                this.OnSeriesPropertyChanging(value);
                this._SeriesProperty = value;
                this.OnSeriesPropertyChanged();
                this.OnPropertyChanged("SeriesProperty");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _SeriesProperty;
        partial void OnSeriesPropertyChanging(global::System.Nullable<int> value);
        partial void OnSeriesPropertyChanged();
        /// <summary>
        /// There are no comments for Property IsDigitalSeries in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("IsDigitalSeries")]
        public virtual global::System.Nullable<global::SAPB1.BoYesNoEnum> IsDigitalSeries
        {
            get
            {
                return this._IsDigitalSeries;
            }
            set
            {
                this.OnIsDigitalSeriesChanging(value);
                this._IsDigitalSeries = value;
                this.OnIsDigitalSeriesChanged();
                this.OnPropertyChanged("IsDigitalSeries");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::SAPB1.BoYesNoEnum> _IsDigitalSeries;
        partial void OnIsDigitalSeriesChanging(global::System.Nullable<global::SAPB1.BoYesNoEnum> value);
        partial void OnIsDigitalSeriesChanged();
        /// <summary>
        /// There are no comments for Property DigitNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DigitNumber")]
        public virtual global::System.Nullable<int> DigitNumber
        {
            get
            {
                return this._DigitNumber;
            }
            set
            {
                this.OnDigitNumberChanging(value);
                this._DigitNumber = value;
                this.OnDigitNumberChanged();
                this.OnPropertyChanged("DigitNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _DigitNumber;
        partial void OnDigitNumberChanging(global::System.Nullable<int> value);
        partial void OnDigitNumberChanged();
        /// <summary>
        /// There are no comments for Property SeriesType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("SeriesType")]
        public virtual global::System.Nullable<global::SAPB1.BoSeriesTypeEnum> SeriesType
        {
            get
            {
                return this._SeriesType;
            }
            set
            {
                this.OnSeriesTypeChanging(value);
                this._SeriesType = value;
                this.OnSeriesTypeChanged();
                this.OnPropertyChanged("SeriesType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::SAPB1.BoSeriesTypeEnum> _SeriesType;
        partial void OnSeriesTypeChanging(global::System.Nullable<global::SAPB1.BoSeriesTypeEnum> value);
        partial void OnSeriesTypeChanged();
        /// <summary>
        /// There are no comments for Property IsManual in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("IsManual")]
        public virtual global::System.Nullable<global::SAPB1.BoYesNoEnum> IsManual
        {
            get
            {
                return this._IsManual;
            }
            set
            {
                this.OnIsManualChanging(value);
                this._IsManual = value;
                this.OnIsManualChanged();
                this.OnPropertyChanged("IsManual");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::SAPB1.BoYesNoEnum> _IsManual;
        partial void OnIsManualChanging(global::System.Nullable<global::SAPB1.BoYesNoEnum> value);
        partial void OnIsManualChanged();
        /// <summary>
        /// There are no comments for Property BPLID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BPLID")]
        public virtual global::System.Nullable<int> BPLID
        {
            get
            {
                return this._BPLID;
            }
            set
            {
                this.OnBPLIDChanging(value);
                this._BPLID = value;
                this.OnBPLIDChanged();
                this.OnPropertyChanged("BPLID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _BPLID;
        partial void OnBPLIDChanging(global::System.Nullable<int> value);
        partial void OnBPLIDChanged();
        /// <summary>
        /// There are no comments for Property ATDocumentType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ATDocumentType")]
        public virtual string ATDocumentType
        {
            get
            {
                return this._ATDocumentType;
            }
            set
            {
                this.OnATDocumentTypeChanging(value);
                this._ATDocumentType = value;
                this.OnATDocumentTypeChanged();
                this.OnPropertyChanged("ATDocumentType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ATDocumentType;
        partial void OnATDocumentTypeChanging(string value);
        partial void OnATDocumentTypeChanged();
        /// <summary>
        /// There are no comments for Property IsElectronicCommEnabled in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("IsElectronicCommEnabled")]
        public virtual global::System.Nullable<global::SAPB1.BoYesNoEnum> IsElectronicCommEnabled
        {
            get
            {
                return this._IsElectronicCommEnabled;
            }
            set
            {
                this.OnIsElectronicCommEnabledChanging(value);
                this._IsElectronicCommEnabled = value;
                this.OnIsElectronicCommEnabledChanged();
                this.OnPropertyChanged("IsElectronicCommEnabled");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::SAPB1.BoYesNoEnum> _IsElectronicCommEnabled;
        partial void OnIsElectronicCommEnabledChanging(global::System.Nullable<global::SAPB1.BoYesNoEnum> value);
        partial void OnIsElectronicCommEnabledChanged();
        /// <summary>
        /// There are no comments for Property CostAccountOnly in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("CostAccountOnly")]
        public virtual global::System.Nullable<global::SAPB1.BoYesNoEnum> CostAccountOnly
        {
            get
            {
                return this._CostAccountOnly;
            }
            set
            {
                this.OnCostAccountOnlyChanging(value);
                this._CostAccountOnly = value;
                this.OnCostAccountOnlyChanged();
                this.OnPropertyChanged("CostAccountOnly");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::SAPB1.BoYesNoEnum> _CostAccountOnly;
        partial void OnCostAccountOnlyChanging(global::System.Nullable<global::SAPB1.BoYesNoEnum> value);
        partial void OnCostAccountOnlyChanged();
        /// <summary>
        /// There are no comments for Property InvoiceType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("InvoiceType")]
        public virtual global::System.Nullable<int> InvoiceType
        {
            get
            {
                return this._InvoiceType;
            }
            set
            {
                this.OnInvoiceTypeChanging(value);
                this._InvoiceType = value;
                this.OnInvoiceTypeChanged();
                this.OnPropertyChanged("InvoiceType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _InvoiceType;
        partial void OnInvoiceTypeChanging(global::System.Nullable<int> value);
        partial void OnInvoiceTypeChanged();
        /// <summary>
        /// There are no comments for Property InvoiceTypeOfNegativeInvoice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("InvoiceTypeOfNegativeInvoice")]
        public virtual global::System.Nullable<int> InvoiceTypeOfNegativeInvoice
        {
            get
            {
                return this._InvoiceTypeOfNegativeInvoice;
            }
            set
            {
                this.OnInvoiceTypeOfNegativeInvoiceChanging(value);
                this._InvoiceTypeOfNegativeInvoice = value;
                this.OnInvoiceTypeOfNegativeInvoiceChanged();
                this.OnPropertyChanged("InvoiceTypeOfNegativeInvoice");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _InvoiceTypeOfNegativeInvoice;
        partial void OnInvoiceTypeOfNegativeInvoiceChanging(global::System.Nullable<int> value);
        partial void OnInvoiceTypeOfNegativeInvoiceChanged();
        /// <summary>
        /// There are no comments for Property PortugalSeriesAction in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PortugalSeriesAction")]
        public virtual string PortugalSeriesAction
        {
            get
            {
                return this._PortugalSeriesAction;
            }
            set
            {
                this.OnPortugalSeriesActionChanging(value);
                this._PortugalSeriesAction = value;
                this.OnPortugalSeriesActionChanged();
                this.OnPropertyChanged("PortugalSeriesAction");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _PortugalSeriesAction;
        partial void OnPortugalSeriesActionChanging(string value);
        partial void OnPortugalSeriesActionChanged();
        /// <summary>
        /// There are no comments for Property PortugalSeriesStatus in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PortugalSeriesStatus")]
        public virtual string PortugalSeriesStatus
        {
            get
            {
                return this._PortugalSeriesStatus;
            }
            set
            {
                this.OnPortugalSeriesStatusChanging(value);
                this._PortugalSeriesStatus = value;
                this.OnPortugalSeriesStatusChanged();
                this.OnPropertyChanged("PortugalSeriesStatus");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _PortugalSeriesStatus;
        partial void OnPortugalSeriesStatusChanging(string value);
        partial void OnPortugalSeriesStatusChanged();
        /// <summary>
        /// There are no comments for Property PortugalSeriesPhase in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PortugalSeriesPhase")]
        public virtual string PortugalSeriesPhase
        {
            get
            {
                return this._PortugalSeriesPhase;
            }
            set
            {
                this.OnPortugalSeriesPhaseChanging(value);
                this._PortugalSeriesPhase = value;
                this.OnPortugalSeriesPhaseChanged();
                this.OnPropertyChanged("PortugalSeriesPhase");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _PortugalSeriesPhase;
        partial void OnPortugalSeriesPhaseChanging(string value);
        partial void OnPortugalSeriesPhaseChanged();
        /// <summary>
        /// There are no comments for Property DynamicProperties in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DynamicProperties")]
        public virtual global::System.Collections.Generic.IDictionary<string, object> DynamicProperties
        {
            get
            {
                return this._DynamicProperties;
            }
            set
            {
                this.OnDynamicPropertiesChanging(value);
                this._DynamicProperties = value;
                this.OnDynamicPropertiesChanged();
                this.OnPropertyChanged("DynamicProperties");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.Generic.IDictionary<string, object> _DynamicProperties = new global::System.Collections.Generic.Dictionary<string, object>();
        partial void OnDynamicPropertiesChanging(global::System.Collections.Generic.IDictionary<string, object> value);
        partial void OnDynamicPropertiesChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
