//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2/9/2023 12:16:29 PM
namespace SAPB1
{
    /// <summary>
    /// There are no comments for SpecialDepreciationMaximumFlagEnum in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("SpecialDepreciationMaximumFlagEnum")]
    public enum SpecialDepreciationMaximumFlagEnum
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("spmfPercentage")]
        SpmfPercentage = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("spmfAmount")]
        SpmfAmount = 1
    }
}
