//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2/9/2023 12:16:29 PM
namespace SAPB1
{
    /// <summary>
    /// There are no comments for SpecialPriceQuantityArea in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("SpecialPriceQuantityArea")]
    public partial class SpecialPriceQuantityArea : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property Quantity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Quantity")]
        public virtual global::System.Nullable<double> Quantity
        {
            get
            {
                return this._Quantity;
            }
            set
            {
                this.OnQuantityChanging(value);
                this._Quantity = value;
                this.OnQuantityChanged();
                this.OnPropertyChanged("Quantity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _Quantity;
        partial void OnQuantityChanging(global::System.Nullable<double> value);
        partial void OnQuantityChanged();
        /// <summary>
        /// There are no comments for Property SPDARowNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("SPDARowNumber")]
        public virtual global::System.Nullable<int> SPDARowNumber
        {
            get
            {
                return this._SPDARowNumber;
            }
            set
            {
                this.OnSPDARowNumberChanging(value);
                this._SPDARowNumber = value;
                this.OnSPDARowNumberChanged();
                this.OnPropertyChanged("SPDARowNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _SPDARowNumber;
        partial void OnSPDARowNumberChanging(global::System.Nullable<int> value);
        partial void OnSPDARowNumberChanged();
        /// <summary>
        /// There are no comments for Property SpecialPrice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("SpecialPrice")]
        public virtual global::System.Nullable<double> SpecialPrice
        {
            get
            {
                return this._SpecialPrice;
            }
            set
            {
                this.OnSpecialPriceChanging(value);
                this._SpecialPrice = value;
                this.OnSpecialPriceChanged();
                this.OnPropertyChanged("SpecialPrice");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _SpecialPrice;
        partial void OnSpecialPriceChanging(global::System.Nullable<double> value);
        partial void OnSpecialPriceChanged();
        /// <summary>
        /// There are no comments for Property ItemNo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("ItemNo")]
        public virtual string ItemNo
        {
            get
            {
                return this._ItemNo;
            }
            set
            {
                this.OnItemNoChanging(value);
                this._ItemNo = value;
                this.OnItemNoChanged();
                this.OnPropertyChanged("ItemNo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ItemNo;
        partial void OnItemNoChanging(string value);
        partial void OnItemNoChanged();
        /// <summary>
        /// There are no comments for Property BPCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BPCode")]
        public virtual string BPCode
        {
            get
            {
                return this._BPCode;
            }
            set
            {
                this.OnBPCodeChanging(value);
                this._BPCode = value;
                this.OnBPCodeChanged();
                this.OnPropertyChanged("BPCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _BPCode;
        partial void OnBPCodeChanging(string value);
        partial void OnBPCodeChanged();
        /// <summary>
        /// There are no comments for Property RowNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("RowNumber")]
        public virtual global::System.Nullable<int> RowNumber
        {
            get
            {
                return this._RowNumber;
            }
            set
            {
                this.OnRowNumberChanging(value);
                this._RowNumber = value;
                this.OnRowNumberChanged();
                this.OnPropertyChanged("RowNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _RowNumber;
        partial void OnRowNumberChanging(global::System.Nullable<int> value);
        partial void OnRowNumberChanged();
        /// <summary>
        /// There are no comments for Property PriceCurrency in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("PriceCurrency")]
        public virtual string PriceCurrency
        {
            get
            {
                return this._PriceCurrency;
            }
            set
            {
                this.OnPriceCurrencyChanging(value);
                this._PriceCurrency = value;
                this.OnPriceCurrencyChanged();
                this.OnPropertyChanged("PriceCurrency");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _PriceCurrency;
        partial void OnPriceCurrencyChanging(string value);
        partial void OnPriceCurrencyChanged();
        /// <summary>
        /// There are no comments for Property Discountin in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Discountin")]
        public virtual global::System.Nullable<double> Discountin
        {
            get
            {
                return this._Discountin;
            }
            set
            {
                this.OnDiscountinChanging(value);
                this._Discountin = value;
                this.OnDiscountinChanged();
                this.OnPropertyChanged("Discountin");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _Discountin;
        partial void OnDiscountinChanging(global::System.Nullable<double> value);
        partial void OnDiscountinChanged();
        /// <summary>
        /// There are no comments for Property UoMEntry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("UoMEntry")]
        public virtual global::System.Nullable<int> UoMEntry
        {
            get
            {
                return this._UoMEntry;
            }
            set
            {
                this.OnUoMEntryChanging(value);
                this._UoMEntry = value;
                this.OnUoMEntryChanged();
                this.OnPropertyChanged("UoMEntry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _UoMEntry;
        partial void OnUoMEntryChanging(global::System.Nullable<int> value);
        partial void OnUoMEntryChanged();
        /// <summary>
        /// There are no comments for Property DynamicProperties in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DynamicProperties")]
        public virtual global::System.Collections.Generic.IDictionary<string, object> DynamicProperties
        {
            get
            {
                return this._DynamicProperties;
            }
            set
            {
                this.OnDynamicPropertiesChanging(value);
                this._DynamicProperties = value;
                this.OnDynamicPropertiesChanged();
                this.OnPropertyChanged("DynamicProperties");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.Generic.IDictionary<string, object> _DynamicProperties = new global::System.Collections.Generic.Dictionary<string, object>();
        partial void OnDynamicPropertiesChanging(global::System.Collections.Generic.IDictionary<string, object> value);
        partial void OnDynamicPropertiesChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
