//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2/9/2023 12:16:29 PM
namespace SAPB1
{
    /// <summary>
    /// There are no comments for StockTransferTaxExtension in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("StockTransferTaxExtension")]
    public partial class StockTransferTaxExtension : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property SupportVAT in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("SupportVAT")]
        public virtual global::System.Nullable<global::SAPB1.BoYesNoEnum> SupportVAT
        {
            get
            {
                return this._SupportVAT;
            }
            set
            {
                this.OnSupportVATChanging(value);
                this._SupportVAT = value;
                this.OnSupportVATChanged();
                this.OnPropertyChanged("SupportVAT");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::SAPB1.BoYesNoEnum> _SupportVAT;
        partial void OnSupportVATChanging(global::System.Nullable<global::SAPB1.BoYesNoEnum> value);
        partial void OnSupportVATChanged();
        /// <summary>
        /// There are no comments for Property FormNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("FormNumber")]
        public virtual string FormNumber
        {
            get
            {
                return this._FormNumber;
            }
            set
            {
                this.OnFormNumberChanging(value);
                this._FormNumber = value;
                this.OnFormNumberChanged();
                this.OnPropertyChanged("FormNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _FormNumber;
        partial void OnFormNumberChanging(string value);
        partial void OnFormNumberChanged();
        /// <summary>
        /// There are no comments for Property TransactionCategory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TransactionCategory")]
        public virtual string TransactionCategory
        {
            get
            {
                return this._TransactionCategory;
            }
            set
            {
                this.OnTransactionCategoryChanging(value);
                this._TransactionCategory = value;
                this.OnTransactionCategoryChanged();
                this.OnPropertyChanged("TransactionCategory");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _TransactionCategory;
        partial void OnTransactionCategoryChanging(string value);
        partial void OnTransactionCategoryChanged();
        /// <summary>
        /// There are no comments for Property U_B1SYS_DIR3_01 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("U_B1SYS_DIR3_01")]
        public virtual string U_B1SYS_DIR3_01
        {
            get
            {
                return this._U_B1SYS_DIR3_01;
            }
            set
            {
                this.OnU_B1SYS_DIR3_01Changing(value);
                this._U_B1SYS_DIR3_01 = value;
                this.OnU_B1SYS_DIR3_01Changed();
                this.OnPropertyChanged("U_B1SYS_DIR3_01");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _U_B1SYS_DIR3_01;
        partial void OnU_B1SYS_DIR3_01Changing(string value);
        partial void OnU_B1SYS_DIR3_01Changed();
        /// <summary>
        /// There are no comments for Property U_B1SYS_DIR3_02 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("U_B1SYS_DIR3_02")]
        public virtual string U_B1SYS_DIR3_02
        {
            get
            {
                return this._U_B1SYS_DIR3_02;
            }
            set
            {
                this.OnU_B1SYS_DIR3_02Changing(value);
                this._U_B1SYS_DIR3_02 = value;
                this.OnU_B1SYS_DIR3_02Changed();
                this.OnPropertyChanged("U_B1SYS_DIR3_02");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _U_B1SYS_DIR3_02;
        partial void OnU_B1SYS_DIR3_02Changing(string value);
        partial void OnU_B1SYS_DIR3_02Changed();
        /// <summary>
        /// There are no comments for Property U_B1SYS_DIR3_03 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("U_B1SYS_DIR3_03")]
        public virtual string U_B1SYS_DIR3_03
        {
            get
            {
                return this._U_B1SYS_DIR3_03;
            }
            set
            {
                this.OnU_B1SYS_DIR3_03Changing(value);
                this._U_B1SYS_DIR3_03 = value;
                this.OnU_B1SYS_DIR3_03Changed();
                this.OnPropertyChanged("U_B1SYS_DIR3_03");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _U_B1SYS_DIR3_03;
        partial void OnU_B1SYS_DIR3_03Changing(string value);
        partial void OnU_B1SYS_DIR3_03Changed();
        /// <summary>
        /// There are no comments for Property DynamicProperties in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DynamicProperties")]
        public virtual global::System.Collections.Generic.IDictionary<string, object> DynamicProperties
        {
            get
            {
                return this._DynamicProperties;
            }
            set
            {
                this.OnDynamicPropertiesChanging(value);
                this._DynamicProperties = value;
                this.OnDynamicPropertiesChanged();
                this.OnPropertyChanged("DynamicProperties");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.Generic.IDictionary<string, object> _DynamicProperties = new global::System.Collections.Generic.Dictionary<string, object>();
        partial void OnDynamicPropertiesChanging(global::System.Collections.Generic.IDictionary<string, object> value);
        partial void OnDynamicPropertiesChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
