//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2/9/2023 12:16:29 PM
namespace SAPB1
{
    /// <summary>
    /// There are no comments for WithholdingTaxData in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("WithholdingTaxData")]
    public partial class WithholdingTaxData : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property WTCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("WTCode")]
        public virtual string WTCode
        {
            get
            {
                return this._WTCode;
            }
            set
            {
                this.OnWTCodeChanging(value);
                this._WTCode = value;
                this.OnWTCodeChanged();
                this.OnPropertyChanged("WTCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _WTCode;
        partial void OnWTCodeChanging(string value);
        partial void OnWTCodeChanged();
        /// <summary>
        /// There are no comments for Property WTAmountSys in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("WTAmountSys")]
        public virtual global::System.Nullable<double> WTAmountSys
        {
            get
            {
                return this._WTAmountSys;
            }
            set
            {
                this.OnWTAmountSysChanging(value);
                this._WTAmountSys = value;
                this.OnWTAmountSysChanged();
                this.OnPropertyChanged("WTAmountSys");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _WTAmountSys;
        partial void OnWTAmountSysChanging(global::System.Nullable<double> value);
        partial void OnWTAmountSysChanged();
        /// <summary>
        /// There are no comments for Property WTAmountFC in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("WTAmountFC")]
        public virtual global::System.Nullable<double> WTAmountFC
        {
            get
            {
                return this._WTAmountFC;
            }
            set
            {
                this.OnWTAmountFCChanging(value);
                this._WTAmountFC = value;
                this.OnWTAmountFCChanged();
                this.OnPropertyChanged("WTAmountFC");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _WTAmountFC;
        partial void OnWTAmountFCChanging(global::System.Nullable<double> value);
        partial void OnWTAmountFCChanged();
        /// <summary>
        /// There are no comments for Property WTAmount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("WTAmount")]
        public virtual global::System.Nullable<double> WTAmount
        {
            get
            {
                return this._WTAmount;
            }
            set
            {
                this.OnWTAmountChanging(value);
                this._WTAmount = value;
                this.OnWTAmountChanged();
                this.OnPropertyChanged("WTAmount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _WTAmount;
        partial void OnWTAmountChanging(global::System.Nullable<double> value);
        partial void OnWTAmountChanged();
        /// <summary>
        /// There are no comments for Property WithholdingType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("WithholdingType")]
        public virtual string WithholdingType
        {
            get
            {
                return this._WithholdingType;
            }
            set
            {
                this.OnWithholdingTypeChanging(value);
                this._WithholdingType = value;
                this.OnWithholdingTypeChanged();
                this.OnPropertyChanged("WithholdingType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _WithholdingType;
        partial void OnWithholdingTypeChanging(string value);
        partial void OnWithholdingTypeChanged();
        /// <summary>
        /// There are no comments for Property TaxableAmountinSys in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TaxableAmountinSys")]
        public virtual global::System.Nullable<double> TaxableAmountinSys
        {
            get
            {
                return this._TaxableAmountinSys;
            }
            set
            {
                this.OnTaxableAmountinSysChanging(value);
                this._TaxableAmountinSys = value;
                this.OnTaxableAmountinSysChanged();
                this.OnPropertyChanged("TaxableAmountinSys");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _TaxableAmountinSys;
        partial void OnTaxableAmountinSysChanging(global::System.Nullable<double> value);
        partial void OnTaxableAmountinSysChanged();
        /// <summary>
        /// There are no comments for Property TaxableAmountFC in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TaxableAmountFC")]
        public virtual global::System.Nullable<double> TaxableAmountFC
        {
            get
            {
                return this._TaxableAmountFC;
            }
            set
            {
                this.OnTaxableAmountFCChanging(value);
                this._TaxableAmountFC = value;
                this.OnTaxableAmountFCChanged();
                this.OnPropertyChanged("TaxableAmountFC");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _TaxableAmountFC;
        partial void OnTaxableAmountFCChanging(global::System.Nullable<double> value);
        partial void OnTaxableAmountFCChanged();
        /// <summary>
        /// There are no comments for Property TaxableAmount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TaxableAmount")]
        public virtual global::System.Nullable<double> TaxableAmount
        {
            get
            {
                return this._TaxableAmount;
            }
            set
            {
                this.OnTaxableAmountChanging(value);
                this._TaxableAmount = value;
                this.OnTaxableAmountChanged();
                this.OnPropertyChanged("TaxableAmount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _TaxableAmount;
        partial void OnTaxableAmountChanging(global::System.Nullable<double> value);
        partial void OnTaxableAmountChanged();
        /// <summary>
        /// There are no comments for Property RoundingType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("RoundingType")]
        public virtual string RoundingType
        {
            get
            {
                return this._RoundingType;
            }
            set
            {
                this.OnRoundingTypeChanging(value);
                this._RoundingType = value;
                this.OnRoundingTypeChanged();
                this.OnPropertyChanged("RoundingType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _RoundingType;
        partial void OnRoundingTypeChanging(string value);
        partial void OnRoundingTypeChanged();
        /// <summary>
        /// There are no comments for Property Rate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Rate")]
        public virtual global::System.Nullable<double> Rate
        {
            get
            {
                return this._Rate;
            }
            set
            {
                this.OnRateChanging(value);
                this._Rate = value;
                this.OnRateChanged();
                this.OnPropertyChanged("Rate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _Rate;
        partial void OnRateChanging(global::System.Nullable<double> value);
        partial void OnRateChanged();
        /// <summary>
        /// There are no comments for Property Criteria in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Criteria")]
        public virtual string Criteria
        {
            get
            {
                return this._Criteria;
            }
            set
            {
                this.OnCriteriaChanging(value);
                this._Criteria = value;
                this.OnCriteriaChanged();
                this.OnPropertyChanged("Criteria");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Criteria;
        partial void OnCriteriaChanging(string value);
        partial void OnCriteriaChanged();
        /// <summary>
        /// There are no comments for Property Category in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Category")]
        public virtual string Category
        {
            get
            {
                return this._Category;
            }
            set
            {
                this.OnCategoryChanging(value);
                this._Category = value;
                this.OnCategoryChanged();
                this.OnPropertyChanged("Category");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Category;
        partial void OnCategoryChanging(string value);
        partial void OnCategoryChanged();
        /// <summary>
        /// There are no comments for Property BaseType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BaseType")]
        public virtual string BaseType
        {
            get
            {
                return this._BaseType;
            }
            set
            {
                this.OnBaseTypeChanging(value);
                this._BaseType = value;
                this.OnBaseTypeChanged();
                this.OnPropertyChanged("BaseType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _BaseType;
        partial void OnBaseTypeChanging(string value);
        partial void OnBaseTypeChanged();
        /// <summary>
        /// There are no comments for Property AppliedWTAmountSys in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AppliedWTAmountSys")]
        public virtual global::System.Nullable<double> AppliedWTAmountSys
        {
            get
            {
                return this._AppliedWTAmountSys;
            }
            set
            {
                this.OnAppliedWTAmountSysChanging(value);
                this._AppliedWTAmountSys = value;
                this.OnAppliedWTAmountSysChanged();
                this.OnPropertyChanged("AppliedWTAmountSys");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _AppliedWTAmountSys;
        partial void OnAppliedWTAmountSysChanging(global::System.Nullable<double> value);
        partial void OnAppliedWTAmountSysChanged();
        /// <summary>
        /// There are no comments for Property AppliedWTAmountFC in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AppliedWTAmountFC")]
        public virtual global::System.Nullable<double> AppliedWTAmountFC
        {
            get
            {
                return this._AppliedWTAmountFC;
            }
            set
            {
                this.OnAppliedWTAmountFCChanging(value);
                this._AppliedWTAmountFC = value;
                this.OnAppliedWTAmountFCChanged();
                this.OnPropertyChanged("AppliedWTAmountFC");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _AppliedWTAmountFC;
        partial void OnAppliedWTAmountFCChanging(global::System.Nullable<double> value);
        partial void OnAppliedWTAmountFCChanged();
        /// <summary>
        /// There are no comments for Property AppliedWTAmount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("AppliedWTAmount")]
        public virtual global::System.Nullable<double> AppliedWTAmount
        {
            get
            {
                return this._AppliedWTAmount;
            }
            set
            {
                this.OnAppliedWTAmountChanging(value);
                this._AppliedWTAmount = value;
                this.OnAppliedWTAmountChanged();
                this.OnPropertyChanged("AppliedWTAmount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<double> _AppliedWTAmount;
        partial void OnAppliedWTAmountChanging(global::System.Nullable<double> value);
        partial void OnAppliedWTAmountChanged();
        /// <summary>
        /// There are no comments for Property GLAccount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("GLAccount")]
        public virtual string GLAccount
        {
            get
            {
                return this._GLAccount;
            }
            set
            {
                this.OnGLAccountChanging(value);
                this._GLAccount = value;
                this.OnGLAccountChanged();
                this.OnPropertyChanged("GLAccount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _GLAccount;
        partial void OnGLAccountChanging(string value);
        partial void OnGLAccountChanged();
        /// <summary>
        /// There are no comments for Property LineNum in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("LineNum")]
        public virtual global::System.Nullable<int> LineNum
        {
            get
            {
                return this._LineNum;
            }
            set
            {
                this.OnLineNumChanging(value);
                this._LineNum = value;
                this.OnLineNumChanged();
                this.OnPropertyChanged("LineNum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _LineNum;
        partial void OnLineNumChanging(global::System.Nullable<int> value);
        partial void OnLineNumChanged();
        /// <summary>
        /// There are no comments for Property BaseDocEntry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BaseDocEntry")]
        public virtual global::System.Nullable<int> BaseDocEntry
        {
            get
            {
                return this._BaseDocEntry;
            }
            set
            {
                this.OnBaseDocEntryChanging(value);
                this._BaseDocEntry = value;
                this.OnBaseDocEntryChanged();
                this.OnPropertyChanged("BaseDocEntry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _BaseDocEntry;
        partial void OnBaseDocEntryChanging(global::System.Nullable<int> value);
        partial void OnBaseDocEntryChanged();
        /// <summary>
        /// There are no comments for Property BaseDocLine in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BaseDocLine")]
        public virtual global::System.Nullable<int> BaseDocLine
        {
            get
            {
                return this._BaseDocLine;
            }
            set
            {
                this.OnBaseDocLineChanging(value);
                this._BaseDocLine = value;
                this.OnBaseDocLineChanged();
                this.OnPropertyChanged("BaseDocLine");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _BaseDocLine;
        partial void OnBaseDocLineChanging(global::System.Nullable<int> value);
        partial void OnBaseDocLineChanged();
        /// <summary>
        /// There are no comments for Property BaseDocType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BaseDocType")]
        public virtual global::System.Nullable<int> BaseDocType
        {
            get
            {
                return this._BaseDocType;
            }
            set
            {
                this.OnBaseDocTypeChanging(value);
                this._BaseDocType = value;
                this.OnBaseDocTypeChanged();
                this.OnPropertyChanged("BaseDocType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _BaseDocType;
        partial void OnBaseDocTypeChanging(global::System.Nullable<int> value);
        partial void OnBaseDocTypeChanged();
        /// <summary>
        /// There are no comments for Property BaseDocumentReference in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("BaseDocumentReference")]
        public virtual global::System.Nullable<int> BaseDocumentReference
        {
            get
            {
                return this._BaseDocumentReference;
            }
            set
            {
                this.OnBaseDocumentReferenceChanging(value);
                this._BaseDocumentReference = value;
                this.OnBaseDocumentReferenceChanged();
                this.OnPropertyChanged("BaseDocumentReference");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _BaseDocumentReference;
        partial void OnBaseDocumentReferenceChanging(global::System.Nullable<int> value);
        partial void OnBaseDocumentReferenceChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("Status")]
        public virtual global::System.Nullable<global::SAPB1.BoStatus> Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this._Status = value;
                this.OnStatusChanged();
                this.OnPropertyChanged("Status");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<global::SAPB1.BoStatus> _Status;
        partial void OnStatusChanging(global::System.Nullable<global::SAPB1.BoStatus> value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property TargetAbsEntry in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TargetAbsEntry")]
        public virtual global::System.Nullable<int> TargetAbsEntry
        {
            get
            {
                return this._TargetAbsEntry;
            }
            set
            {
                this.OnTargetAbsEntryChanging(value);
                this._TargetAbsEntry = value;
                this.OnTargetAbsEntryChanged();
                this.OnPropertyChanged("TargetAbsEntry");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _TargetAbsEntry;
        partial void OnTargetAbsEntryChanging(global::System.Nullable<int> value);
        partial void OnTargetAbsEntryChanged();
        /// <summary>
        /// There are no comments for Property TargetDocumentType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("TargetDocumentType")]
        public virtual global::System.Nullable<int> TargetDocumentType
        {
            get
            {
                return this._TargetDocumentType;
            }
            set
            {
                this.OnTargetDocumentTypeChanging(value);
                this._TargetDocumentType = value;
                this.OnTargetDocumentTypeChanged();
                this.OnPropertyChanged("TargetDocumentType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Nullable<int> _TargetDocumentType;
        partial void OnTargetDocumentTypeChanging(global::System.Nullable<int> value);
        partial void OnTargetDocumentTypeChanged();
        /// <summary>
        /// There are no comments for Property DynamicProperties in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]

        [global::Microsoft.OData.Client.OriginalNameAttribute("DynamicProperties")]
        public virtual global::System.Collections.Generic.IDictionary<string, object> DynamicProperties
        {
            get
            {
                return this._DynamicProperties;
            }
            set
            {
                this.OnDynamicPropertiesChanging(value);
                this._DynamicProperties = value;
                this.OnDynamicPropertiesChanged();
                this.OnPropertyChanged("DynamicProperties");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Collections.Generic.IDictionary<string, object> _DynamicProperties = new global::System.Collections.Generic.Dictionary<string, object>();
        partial void OnDynamicPropertiesChanging(global::System.Collections.Generic.IDictionary<string, object> value);
        partial void OnDynamicPropertiesChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
